import 'package:flutter/material.dart';
import 'package:saiyome/screens/budget_page.dart';
import 'package:saiyome/screens/monthly_report_page.dart';
import 'package:saiyome/screens/report_page.dart';
import 'package:saiyome/screens/backup_restore_page.dart';
import 'package:saiyome/screens/premium_page.dart';
import 'package:purchases_flutter/purchases_flutter.dart';
import 'package:saiyome/widgets/future_log_item.dart';
import 'package:saiyome/widgets/roast_card.dart';
import 'package:saiyome/widgets/summary_card.dart';
import 'package:saiyome/widgets/timeline_item.dart';
import 'package:saiyome/screens/add_expense_page.dart';
import 'package:saiyome/models/expense.dart';
import 'package:saiyome/models/budget_history.dart';
import 'package:saiyome/models/isar_service.dart';
import 'package:intl/intl.dart';
import 'package:saiyome/services/roast_service.dart';
import 'package:saiyome/services/expense_judge_service.dart';
import 'package:saiyome/services/remaining_budget_service.dart';
import 'package:saiyome/screens/timeline_page.dart';
import 'package:saiyome/screens/ranking_page.dart';
import 'package:saiyome/screens/money_usage_page.dart';
import 'package:saiyome/screens/rank_detail_page.dart';
import 'package:saiyome/services/rank_service.dart';
import 'package:saiyome/services/budget_history_service.dart';
import 'package:saiyome/services/monthly_report_service.dart';
import 'package:saiyome/services/expense_sync_service.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:flutter/foundation.dart';
import 'package:saiyome/utils/time_provider.dart';
import 'package:saiyome/main.dart' show flutterLocalNotificationsPlugin;

class HomePage extends StatefulWidget {
  const HomePage({super.key});

  @override
  State<HomePage> createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  List<Expense> _expenses = [];
  BudgetSetting? _budgetSetting;
  RankResult? _rankResult;
  bool _isPremium = false;
  bool _hasLoadedPremium = false;
  bool _isInitialLoading = true;
  List<Expense> _currentCycleExpensesCache = [];
  int _usedAmountCache = 0;
  int _remainingBudgetCache = 0;
  int _realWalletLifeDaysCache = 0;
  int _dailySpendingPaceYenCache = 0;
  int _plannedDailyBudgetYenCache = 0;
  List<Map<String, dynamic>> _categorySummariesCache = [];
  List<Map<String, dynamic>> _dangerCategoriesCache = [];
  List<({String title, String message, String subMessage})> _roastCardsCache = [];
  RemainingBudgetResult _remainingBudgetResultCache = const RemainingBudgetResult(
    title: '',
    message: '',
    subMessage: '',
  );
  bool _hasAutoGeneratedMonthlyReport = false;
  bool _isGeneratingMonthlyReport = false;
  String? _monthlyReportStatusMessage;
  BudgetHistory? _currentBudgetHistory;

  User? get _currentUser => Supabase.instance.client.auth.currentUser;

  bool get _isLoggedIn {
    final user = _currentUser;
    return user != null && !user.isAnonymous;
  }

  int _cycleOffsetMonths = 0;
  final ScrollController _categoryScrollController = ScrollController();

@override
void initState() {
  super.initState();
  _initPage();
}

Future<void> _initPage() async {
  await ensureDebugTimeLoaded();
  await _loadInitialData();
}

  @override
  void dispose() {
    _categoryScrollController.dispose();
    super.dispose();
  }

Future<void> _loadInitialData() async {
  if (mounted) {
    setState(() {
      _isInitialLoading = true;
    });
  }

  await _syncBudgetHistoryIfNeeded();
  await _loadBudgetSetting();
  await _loadPremiumStatus();

  if (_isPremium && !_hasAutoGeneratedMonthlyReport) {
    await _autoGenerateMonthlyReportIfNeeded();
    _hasAutoGeneratedMonthlyReport = true;
  }

  await Future.wait([
    _loadExpenses(),
    _loadRankData(),
  ]);

  if (mounted) {
    setState(() {
      _isInitialLoading = false;
    });
  }
}

Future<void> _syncBudgetHistoryIfNeeded() async {
  final budgetSetting = await IsarService.getBudgetSetting();
  if (budgetSetting == null) return;
  if (budgetSetting.totalBudget <= 0) return;

  await BudgetHistoryService.syncIfNeeded(
    cycleStartDay: budgetSetting.cycleStartDay,
    totalBudget: budgetSetting.totalBudget,
  );

  _currentBudgetHistory = null;
}

  Future<void> _recomputeDerivedCaches() async {
    final start = _currentCycleStart;
    final endExclusive = _currentCycleEndExclusive;
    final endInclusive = _currentCycleEnd;

    final currentCycleExpenses = _expenses.where((expense) {
      final createdAt = expense.createdAt;
      return !createdAt.isBefore(start) && createdAt.isBefore(endExclusive);
    }).toList();

    final usedAmount = currentCycleExpenses.fold<int>(
      0,
      (sum, expense) => sum + expense.amount,
    );

    final totalBudget = _totalBudget;
    final remainingBudgetRaw = totalBudget - usedAmount;
    final remainingBudget = remainingBudgetRaw < 0 ? 0 : remainingBudgetRaw;

    int realWalletLifeDays = 0;
    if (_cycleOffsetMonths == 0 && totalBudget > 0 && remainingBudget > 0) {
      final totalCycleDays = endInclusive.difference(start).inDays;
      if (totalCycleDays > 0) {
        final plannedDailyBudget = totalBudget / totalCycleDays;
        if (plannedDailyBudget > 0) {
          realWalletLifeDays =
              (remainingBudget / plannedDailyBudget).ceil().clamp(1, 999);
        }
      }
    }

    int dailySpendingPaceYen = 0;
    if (_cycleOffsetMonths == 0 && usedAmount > 0) {
      // final now = DateTime.now();
      final now = getNow();
      final today = DateTime(now.year, now.month, now.day);
      final normalizedCycleStart = DateTime(start.year, start.month, start.day);
      final elapsedDays = today.difference(normalizedCycleStart).inDays + 1;
      if (elapsedDays > 0) {
        dailySpendingPaceYen = (usedAmount / elapsedDays).round();
      }
    }

    int plannedDailyBudgetYen = 0;
    if (_cycleOffsetMonths == 0 && totalBudget > 0) {
      final totalCycleDays = endInclusive.difference(start).inDays;
      if (totalCycleDays > 0) {
        plannedDailyBudgetYen = (totalBudget / totalCycleDays).round();
      }
    }

    final categories = _budgetSetting?.categories ?? [];
    final categorySummaries = categories.map((category) {
      final used = currentCycleExpenses
          .where((expense) => expense.category == category.name)
          .fold<int>(0, (sum, expense) => sum + expense.amount);
      final remaining = category.budget - used;
      final usageRate = category.budget == 0 ? 0.0 : used / category.budget;

      return {
        'name': category.name,
        'badge': category.badge,
        'budget': category.budget,
        'used': used,
        'remaining': remaining,
        'usageRate': usageRate,
      };
    }).toList();

    final dangerCategories = categorySummaries.where((category) {
      final budget = category['budget'] as int;
      if (budget == 0) return false;

      final usageRate = category['usageRate'] as double;
      final remaining = category['remaining'] as int;
      return remaining < 0 || usageRate >= 0.75;
    }).toList();

    dangerCategories.sort((a, b) {
      final aRate = a['usageRate'] as double;
      final bRate = b['usageRate'] as double;
      return bRate.compareTo(aRate);
    });

    final roastCards = await _buildRoastCards(
      currentCycleExpenses: currentCycleExpenses,
      totalBudget: totalBudget,
      usedAmount: usedAmount,
      start: start,
      endInclusive: endInclusive,
      dangerCategories: dangerCategories,
    );

    final remainingBudgetResult = RemainingBudgetService.build(
      totalBudget: totalBudget,
      usedAmount: usedAmount,
      cycleStart: start,
      cycleEnd: endInclusive,
    );

    if (!mounted) return;

    setState(() {
    _currentCycleExpensesCache = currentCycleExpenses;
    _usedAmountCache = usedAmount;
    _remainingBudgetCache = remainingBudget;
    _realWalletLifeDaysCache = realWalletLifeDays;
    _dailySpendingPaceYenCache = dailySpendingPaceYen;
    _plannedDailyBudgetYenCache = plannedDailyBudgetYen;
    _categorySummariesCache = categorySummaries;
    _dangerCategoriesCache = dangerCategories.take(3).toList();
    _roastCardsCache = roastCards;
    _remainingBudgetResultCache = remainingBudgetResult;
    });
  }

  Future<void> _loadExpenses() async {
    final expenses = await IsarService.getExpenses();
    if (!mounted) return;

    setState(() {
      _expenses = expenses;
    });

    await _recomputeDerivedCaches();
  }

  Future<void> _loadBudgetSetting() async {
    final budgetSetting = await IsarService.getBudgetSetting();
    if (budgetSetting == null) return;

    final histories = await IsarService.getBudgetHistories();
    final now = getNow();

    BudgetHistory? currentHistory;
    for (final history in histories) {
      if (!now.isBefore(history.startDate) && now.isBefore(history.endDate)) {
        currentHistory = history;
        break;
      }
    }

    if (!mounted) return;

    setState(() {
      _budgetSetting = budgetSetting;
      _currentBudgetHistory = currentHistory;
    });

    await _recomputeDerivedCaches();
  }

  Future<void> _loadRankData() async {
  final histories = await IsarService.getBudgetHistories();
  if (!mounted) return;
  setState(() {
    _rankResult = RankService.calculate(histories);
  });
}

  Future<void> _loadPremiumStatus() async {
    if (_hasLoadedPremium) return;

    try {
      final customerInfo = await Purchases.getCustomerInfo();
      if (!mounted) return;
      setState(() {
        _isPremium = customerInfo.entitlements.active.containsKey('premium');
        _hasLoadedPremium = true;
      });
    } catch (_) {
      if (!mounted) return;
      setState(() {
        _isPremium = false;
        _hasLoadedPremium = true;
      });
    }
  }

  IconData _iconForCategory(String category) {
    switch (category) {
      case 'カフェ':
        return Icons.local_cafe_outlined;
      case 'コンビニ':
        return Icons.storefront_outlined;
      case '外食':
        return Icons.restaurant_outlined;
      case '日用品':
        return Icons.shopping_bag_outlined;
      case '趣味':
        return Icons.sports_esports_outlined;
      case '食費':
      default:
        return Icons.receipt_long_outlined;
    }
  }


  int get _cycleStartDay {
    final day = _budgetSetting?.cycleStartDay ?? 1;
    return day.clamp(1, 28);
  }

({DateTime start, DateTime endExclusive}) _resolvedCurrentCycleRange() {
  if (_cycleOffsetMonths == 0 && _currentBudgetHistory != null) {
    return (
      start: _currentBudgetHistory!.startDate,
      endExclusive: _currentBudgetHistory!.endDate,
    );
  }

  final now = getNow();
  final startDay = _cycleStartDay.clamp(1, 28);

  final baseStart = now.day >= startDay
      ? DateTime(now.year, now.month, startDay)
      : DateTime(now.year, now.month - 1, startDay);

  final start = DateTime(
    baseStart.year,
    baseStart.month + _cycleOffsetMonths,
    baseStart.day,
  );
  final endExclusive = DateTime(start.year, start.month + 1, startDay);

  return (start: start, endExclusive: endExclusive);
}

DateTime get _currentCycleStart => _resolvedCurrentCycleRange().start;

DateTime get _currentCycleEndExclusive =>
    _resolvedCurrentCycleRange().endExclusive;

DateTime get _currentCycleEnd {
  final endExclusive = _currentCycleEndExclusive;
  return endExclusive.subtract(const Duration(days: 1));
}


  int get _totalBudget {
    return _budgetSetting?.totalBudget ?? 0;
  }


  int _remainingPeriodDays() {
  // final now = DateTime.now();
  final now = getNow();
  final today = DateTime(now.year, now.month, now.day);
  final end = DateTime(
    _currentCycleEnd.year,
    _currentCycleEnd.month,
    _currentCycleEnd.day,
  );

  final diff = end.difference(today).inDays;
  return diff < 0 ? 0 : diff;
}


  String _formatYen(int value) {
    final formatter = NumberFormat('#,###');
    return formatter.format(value);
  }

String _formatTimelineDate(DateTime date) {
  // final now = DateTime.now();
  final now = getNow();
  final today = DateTime(now.year, now.month, now.day);
  final target = DateTime(date.year, date.month, date.day);

  final diff = today.difference(target).inDays;

  if (diff == 0) return '今日';
  if (diff == 1) return '昨日';

  return DateFormat('M/d').format(date);
}

String _formatCyclePeriod() {
  final start = _currentCycleStart;
  final end = _currentCycleEnd;
  return '${start.month}/${start.day} 〜 ${end.month}/${end.day}';
}

Widget _rankBadge(String? rankKey, {double size = 52}) {
  Color color;

  switch (rankKey) {
    case 'diamond':
      color = const Color(0xFF8B5CF6);
      break;
    case 'platinum':
      color = const Color(0xFF94A3B8);
      break;
    case 'gold':
      color = const Color(0xFFF5B700);
      break;
    case 'silver':
      color = const Color(0xFFB8C2CC);
      break;
    case 'bronze':
      color = const Color(0xFFC47A44);
      break;
    default:
      color = const Color(0xFFA3A3A3);
  }

  return Container(
    width: size,
    height: size,
    alignment: Alignment.center,
    decoration: BoxDecoration(
      color: color,
      shape: BoxShape.circle,
      border: Border.all(color: Colors.black.withOpacity(0.05)),
      boxShadow: [
        BoxShadow(
          color: Colors.black.withOpacity(0.06),
          blurRadius: 10,
          offset: const Offset(0, 4),
        ),
      ],
    ),
    child: Icon(
      Icons.auto_graph_rounded,
      color: Colors.white,
      size: size * 0.42,
    ),
  );

}

// Receipt overlay helpers
List<_ReceiptDecorationItem> _buildReceiptDecorations({
  required double usageRate,
}) {
  return const [];
}

String? _receiptOverlayLabel(double usageRate) {
  return null;
}

Widget _buildSummaryReceiptOverlay({
  required ThemeData theme,
  required double usageRate,
}) {
  final receipts = _buildReceiptDecorations(usageRate: usageRate);
  if (receipts.isEmpty) {
    return const SizedBox.shrink();
  }

  final overlayLabel = _receiptOverlayLabel(usageRate);

  return IgnorePointer(
    child: SizedBox(
      height: usageRate >= 1.0 ? 230 : 190,
      child: Stack(
        clipBehavior: Clip.none,
        children: [
          for (final receipt in receipts)
            Positioned(
              left: receipt.left,
              right: receipt.right,
              top: receipt.top - 92,
              child: Transform.rotate(
                angle: receipt.rotation,
                child: Opacity(
                  opacity: receipt.opacity,
                  child: _ReceiptDecorationCard(width: receipt.width),
                ),
              ),
            ),
          if (overlayLabel != null)
            Positioned(
              left: 18,
              right: 18,
              bottom: usageRate >= 1.0 ? 0 : 8,
              child: Align(
                alignment: Alignment.centerLeft,
                child: Container(
                  padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
                  decoration: BoxDecoration(
                    color: Colors.white.withOpacity(0.96),
                    borderRadius: BorderRadius.circular(999),
                    border: Border.all(color: const Color(0xFFE8E8E8)),
                  ),
                  child: Text(
                    overlayLabel,
                    style: theme.textTheme.bodySmall?.copyWith(
                      fontWeight: FontWeight.w700,
                      color: Colors.black87,
                    ),
                  ),
                ),
              ),
            ),
        ],
      ),
    ),
  );
}

List<_ReceiptDecorationItem> _buildFullScreenReceiptDecorations({
  required double usageRate,
}) {
  if (usageRate < 0.75) return const [];

  if (usageRate < 0.9) {
    return const [
      _ReceiptDecorationItem(left: 18, top: 170, width: 108, rotation: -0.16, opacity: 0.14),
      _ReceiptDecorationItem(right: 22, top: 206, width: 102, rotation: 0.14, opacity: 0.13),
      _ReceiptDecorationItem(left: 96, top: 252, width: 96, rotation: -0.08, opacity: 0.12),
      _ReceiptDecorationItem(right: 102, top: 332, width: 94, rotation: 0.08, opacity: 0.12),
      _ReceiptDecorationItem(left: 26, top: 408, width: 98, rotation: -0.1, opacity: 0.13),
      _ReceiptDecorationItem(right: 30, top: 494, width: 92, rotation: 0.08, opacity: 0.12),
    ];
  }

  if (usageRate < 1.0) {
    return const [
      _ReceiptDecorationItem(left: 14, top: 144, width: 112, rotation: -0.18, opacity: 0.18),
      _ReceiptDecorationItem(right: 18, top: 184, width: 106, rotation: 0.16, opacity: 0.17),
      _ReceiptDecorationItem(left: 88, top: 228, width: 102, rotation: -0.1, opacity: 0.16),
      _ReceiptDecorationItem(right: 88, top: 292, width: 100, rotation: 0.12, opacity: 0.16),
      _ReceiptDecorationItem(left: 20, top: 358, width: 104, rotation: -0.12, opacity: 0.17),
      _ReceiptDecorationItem(right: 22, top: 424, width: 96, rotation: 0.1, opacity: 0.16),
      _ReceiptDecorationItem(left: 106, top: 500, width: 94, rotation: -0.08, opacity: 0.15),
      _ReceiptDecorationItem(right: 34, top: 568, width: 92, rotation: 0.08, opacity: 0.14),
    ];
  }

  if (usageRate < 1.1) {
    return const [
      _ReceiptDecorationItem(left: 10, top: 120, width: 114, rotation: -0.2, opacity: 0.21),
      _ReceiptDecorationItem(right: 12, top: 154, width: 110, rotation: 0.18, opacity: 0.2),
      _ReceiptDecorationItem(left: 84, top: 200, width: 104, rotation: -0.12, opacity: 0.19),
      _ReceiptDecorationItem(right: 86, top: 258, width: 100, rotation: 0.14, opacity: 0.18),
      _ReceiptDecorationItem(left: 18, top: 318, width: 104, rotation: -0.14, opacity: 0.19),
      _ReceiptDecorationItem(right: 18, top: 382, width: 98, rotation: 0.12, opacity: 0.18),
      _ReceiptDecorationItem(left: 102, top: 454, width: 96, rotation: -0.08, opacity: 0.17),
      _ReceiptDecorationItem(right: 28, top: 522, width: 94, rotation: 0.08, opacity: 0.17),
      _ReceiptDecorationItem(left: 116, top: 590, width: 90, rotation: -0.06, opacity: 0.16),
    ];
  }

  if (usageRate < 1.2) {
    return const [
      _ReceiptDecorationItem(left: 8, top: 108, width: 116, rotation: -0.22, opacity: 0.24),
      _ReceiptDecorationItem(right: 10, top: 142, width: 112, rotation: 0.2, opacity: 0.23),
      _ReceiptDecorationItem(left: 76, top: 188, width: 108, rotation: -0.12, opacity: 0.22),
      _ReceiptDecorationItem(right: 76, top: 242, width: 104, rotation: 0.14, opacity: 0.21),
      _ReceiptDecorationItem(left: 14, top: 304, width: 106, rotation: -0.14, opacity: 0.22),
      _ReceiptDecorationItem(right: 16, top: 364, width: 100, rotation: 0.12, opacity: 0.2),
      _ReceiptDecorationItem(left: 94, top: 430, width: 100, rotation: -0.1, opacity: 0.19),
      _ReceiptDecorationItem(right: 24, top: 496, width: 96, rotation: 0.1, opacity: 0.19),
      _ReceiptDecorationItem(left: 112, top: 560, width: 94, rotation: -0.08, opacity: 0.18),
      _ReceiptDecorationItem(right: 34, top: 622, width: 90, rotation: 0.08, opacity: 0.18),
      _ReceiptDecorationItem(left: 126, top: 686, width: 88, rotation: -0.06, opacity: 0.17),
    ];
  }

  return const [
    _ReceiptDecorationItem(left: 6, top: 94, width: 118, rotation: -0.24, opacity: 0.27),
    _ReceiptDecorationItem(right: 8, top: 126, width: 114, rotation: 0.22, opacity: 0.26),
    _ReceiptDecorationItem(left: 72, top: 170, width: 110, rotation: -0.12, opacity: 0.24),
    _ReceiptDecorationItem(right: 70, top: 222, width: 106, rotation: 0.16, opacity: 0.23),
    _ReceiptDecorationItem(left: 10, top: 286, width: 108, rotation: -0.14, opacity: 0.23),
    _ReceiptDecorationItem(right: 12, top: 344, width: 104, rotation: 0.12, opacity: 0.22),
    _ReceiptDecorationItem(left: 86, top: 410, width: 102, rotation: -0.1, opacity: 0.21),
    _ReceiptDecorationItem(right: 20, top: 474, width: 100, rotation: 0.1, opacity: 0.2),
    _ReceiptDecorationItem(left: 108, top: 538, width: 98, rotation: -0.08, opacity: 0.2),
    _ReceiptDecorationItem(right: 28, top: 602, width: 96, rotation: 0.08, opacity: 0.19),
    _ReceiptDecorationItem(left: 120, top: 666, width: 92, rotation: -0.06, opacity: 0.18),
    _ReceiptDecorationItem(right: 40, top: 726, width: 90, rotation: 0.08, opacity: 0.18),
    _ReceiptDecorationItem(left: 92, top: 786, width: 88, rotation: -0.06, opacity: 0.17),
  ];
}

Widget _buildFullScreenReceiptOverlay({
  required double usageRate,
}) {
  final receipts = _buildFullScreenReceiptDecorations(usageRate: usageRate);
  if (receipts.isEmpty) {
    return const SizedBox.shrink();
  }

  return IgnorePointer(
    child: Stack(
      clipBehavior: Clip.none,
      children: [
        Positioned.fill(
          child: DecoratedBox(
            decoration: BoxDecoration(
              gradient: LinearGradient(
                begin: Alignment.topCenter,
                end: Alignment.bottomCenter,
                colors: [
                  Colors.transparent,
                  Colors.white.withOpacity(0.02),
                  Colors.white.withOpacity(usageRate >= 1.2 ? 0.08 : 0.05),
                ],
                stops: const [0.0, 0.38, 1.0],
              ),
            ),
          ),
        ),
        for (final receipt in receipts)
          Positioned(
            left: receipt.left,
            right: receipt.right,
            top: receipt.top,
            child: Transform.rotate(
              angle: receipt.rotation,
              child: Opacity(
                opacity: receipt.opacity,
                child: _ReceiptDecorationCard(width: receipt.width),
              ),
            ),
          ),
      ],
    ),
  );
}

Future<void> _shiftDebugNow(Duration delta) async {
  final base = getNow();
  await setDebugNow(base.add(delta));
  if (!mounted) return;
  await _loadInitialData();
}

Future<void> _resetDebugNow() async {
  await clearDebugNow();
  if (!mounted) return;
  await _loadInitialData();
}

Future<void> _openDebugTimeMenu() async {
  if (!kDebugMode) return;

  await showModalBottomSheet<void>(
    context: context,
    isScrollControlled: true,
    builder: (sheetContext) {
      final now = getNow();
      return SafeArea(
        child: FractionallySizedBox(
          heightFactor: 0.72,
          child: Column(
            mainAxisSize: MainAxisSize.max,
            children: [
              const SizedBox(height: 8),
              Container(
                width: 42,
                height: 4,
                decoration: BoxDecoration(
                  color: const Color(0xFFD6D6D6),
                  borderRadius: BorderRadius.circular(999),
                ),
              ),
              ListTile(
                title: const Text('デバッグ時刻'),
                subtitle: Text(DateFormat('yyyy/MM/dd').format(now)),
              ),
              Expanded(
                child: ListView(
                  children: [
                    ListTile(
                      leading: const Icon(Icons.remove),
                      title: const Text('-1日'),
                      onTap: () async {
                        Navigator.pop(sheetContext);
                        await _shiftDebugNow(const Duration(days: -1));
                      },
                    ),
                    ListTile(
                      leading: const Icon(Icons.add),
                      title: const Text('+1日'),
                      onTap: () async {
                        Navigator.pop(sheetContext);
                        await _shiftDebugNow(const Duration(days: 1));
                      },
                    ),
                    ListTile(
                      leading: const Icon(Icons.remove),
                      title: const Text('-7日'),
                      onTap: () async {
                        Navigator.pop(sheetContext);
                        await _shiftDebugNow(const Duration(days: -7));
                      },
                    ),
                    ListTile(
                      leading: const Icon(Icons.add),
                      title: const Text('+7日'),
                      onTap: () async {
                        Navigator.pop(sheetContext);
                        await _shiftDebugNow(const Duration(days: 7));
                      },
                    ),
                    ListTile(
                      leading: const Icon(Icons.remove),
                      title: const Text('-30日'),
                      onTap: () async {
                        Navigator.pop(sheetContext);
                        await _shiftDebugNow(const Duration(days: -30));
                      },
                    ),
                    ListTile(
                      leading: const Icon(Icons.add),
                      title: const Text('+30日'),
                      onTap: () async {
                        Navigator.pop(sheetContext);
                        await _shiftDebugNow(const Duration(days: 30));
                      },
                    ),
                    ListTile(
                      leading: const Icon(Icons.refresh),
                      title: const Text('現在に戻す'),
                      onTap: () async {
                        Navigator.pop(sheetContext);
                        await _resetDebugNow();
                      },
                    ),
                  ],
                ),
              ),
              const SizedBox(height: 12),
            ],
          ),
        ),
      );
    },
  );
}

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final currentUser = _currentUser;
    final isLoggedIn = _isLoggedIn;
    final currentCycleStart = _currentCycleStart;
    final currentCycleEnd = _currentCycleEnd;
    final currentCycleExpenses = _currentCycleExpensesCache;
    final usedAmount = _usedAmountCache;
    final remainingBudget = _remainingBudgetCache;
    final realWalletLifeDays = _realWalletLifeDaysCache;
    final remainingPeriodDays = _remainingPeriodDays();
    final remainingBudgetResult = _remainingBudgetResultCache;
    final dailySpendingPaceYen = _dailySpendingPaceYenCache;
    final plannedDailyBudgetYen = _plannedDailyBudgetYenCache;
    final cyclePeriodText = _formatCyclePeriod();
    final dangerCategories = _dangerCategoriesCache;
    final roastCards = _roastCardsCache;
    final categorySummaries = _categorySummariesCache;
    final budgetUsageRate = _totalBudget <= 0 ? 0.0 : usedAmount / _totalBudget;
    final hasReceiptOverlay = budgetUsageRate >= 0.75;
   final hasFullScreenReceiptOverlay = budgetUsageRate >= 0.75;

    return Scaffold(
      drawer: Drawer(
        shape: const RoundedRectangleBorder(
          borderRadius: BorderRadius.only(
            topRight: Radius.circular(24),
            bottomRight: Radius.circular(24),
          ),
        ),
        child: SafeArea(
          child: ListView(
            padding: EdgeInsets.zero,
            children: [
              Container(
                width: double.infinity,
                padding: const EdgeInsets.fromLTRB(20, 24, 20, 18),
                decoration: const BoxDecoration(
                  color: Color(0xFFF8F9FC),
                  border: Border(
                    bottom: BorderSide(color: Color(0xFFE9ECF3)),
                  ),
                ),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Container(
                      width: 44,
                      height: 44,
                      decoration: BoxDecoration(
                        color: Colors.white,
                        borderRadius: BorderRadius.circular(14),
                      ),
                      alignment: Alignment.center,
                      child: const Icon(
                        Icons.account_balance_wallet_outlined,
                        size: 24,
                        color: Color(0xFFFF8A65),
                      ),
                    ),
                    const SizedBox(height: 14),
                    Text(
                      '財布の余命',
                      style: theme.textTheme.titleLarge?.copyWith(
                        fontWeight: FontWeight.w800,
                        color: Colors.black87,
                      ),
                    ),
                    const SizedBox(height: 4),
                    Text(
                      '設定・機能一覧',
                      style: theme.textTheme.bodySmall?.copyWith(
                        color: Colors.black54,
                        fontWeight: FontWeight.w500,
                      ),
                    ),
                  ],
                ),
              ),
              Padding(
                padding: const EdgeInsets.fromLTRB(12, 12, 12, 20),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    if (kDebugMode) ...[
                      Container(
                        width: double.infinity,
                        margin: const EdgeInsets.only(bottom: 12),
                        padding: const EdgeInsets.all(12),
                        decoration: BoxDecoration(
                          color: const Color(0xFFF8F9FC),
                          borderRadius: BorderRadius.circular(16),
                          border: Border.all(color: const Color(0xFFE6E9F2)),
                        ),
                        child: Text(
                          'デバッグ時刻: ${DateFormat('yyyy/MM/dd').format(getNow())}',
                          style: theme.textTheme.bodySmall?.copyWith(
                            fontWeight: FontWeight.w700,
                            color: Colors.black87,
                          ),
                        ),
                      ),
                    ],
                    _DrawerSectionLabel(
                      title: 'アカウント',
                      theme: theme,
                    ),
                    _DrawerTile(
                      icon: isLoggedIn
                          ? Icons.verified_user_outlined
                          : Icons.person_outline,
                      title: isLoggedIn ? 'ログイン中' : '未ログイン',
                      subtitle: isLoggedIn
                          ? (currentUser?.email?.isNotEmpty == true
                              ? currentUser!.email!
                              : 'Apple / Google アカウントで利用中')
                          : 'アカウント登録・ログインで引き継ぎできます',
                      onTap: () async {
                        Navigator.pop(context);
                        final result = await Navigator.push(
                          context,
                          MaterialPageRoute(
                            builder: (_) => const BackupRestorePage(),
                          ),
                        );
                        if (result == true) {
                          await _loadInitialData();
                        }
                      },
                    ),
                    const SizedBox(height: 14),
                    _DrawerSectionLabel(
                      title: 'プレミアム',
                      theme: theme,
                    ),
                    _DrawerTile(
                      icon: Icons.workspace_premium_rounded,
                      title: _isPremium ? 'プレミアム利用中' : 'プレミアム',
                      subtitle: _isPremium
                          ? 'すべてのプレミアム機能が使えます'
                          : 'レポート・バッヂ・バックアップ・レシート機能を解放',
                      onTap: () async {
                        Navigator.pop(context);
                        final result = await Navigator.push(
                          context,
                          MaterialPageRoute(
                            builder: (_) => const PremiumPage(),
                          ),
                        );
                        if (result == true) {
                          await _loadPremiumStatus();
                        }
                      },
                    ),
                    _DrawerTile(
                      icon: Icons.credit_card_outlined,
                      title: 'クレカ連携…？',
                      subtitle: '自動連携について',
                      onTap: () async {
                        Navigator.pop(context);

                        final confirm = await showDialog<bool>(
                          context: context,
                          builder: (dialogContext) {
                            return AlertDialog(
                              title: const Text('本当に連携しますか？'),
                              content: const Text('クレジットカードと連携して、自動で記録しますか？'),
                              actions: [
                                TextButton(
                                  onPressed: () => Navigator.pop(dialogContext, false),
                                  child: const Text('やめる'),
                                ),
                                TextButton(
                                  onPressed: () => Navigator.pop(dialogContext, true),
                                  child: const Text('はい'),
                                ),
                              ],
                            );
                          },
                        );

                        if (confirm != true) return;

                        if (!context.mounted) return;

                        await showDialog(
                          context: context,
                          builder: (dialogContext) {
                            return AlertDialog(
                              title: const Text('クレカ連携、ありません笑'),
                              content: const Text(
                                'このアプリは、あえて自動連携をしていません。\n\n'
                                '入力するひと手間が、使いすぎへの気づきにつながるからです。\n\n'
                                '少し面倒ですが、いっしょに財布と向き合っていきましょう。\n\n'
                                '👉 まずは今日の支出を1つだけ記録してみましょう。'
                              ),
                              actions: [
                                TextButton(
                                  onPressed: () => Navigator.pop(dialogContext),
                                  child: const Text('OK'),
                                ),
                              ],
                            );
                          },
                        );
                      },
                    ),
                    const SizedBox(height: 14),
                    _DrawerSectionLabel(
                      title: '機能',
                      theme: theme,
                    ),
                    _DrawerTile(
                      icon: Icons.savings_outlined,
                      title: '予算設定',
                      onTap: () async {
                        Navigator.pop(context);
                        final result = await Navigator.push(
                          context,
                          MaterialPageRoute(
                            builder: (_) => const BudgetPage(),
                          ),
                        );
                        if (result == true) {
                          await _loadInitialData();
                        }
                      },
                    ),
                    _DrawerTile(
                      icon: Icons.summarize_outlined,
                      title: '今週のまとめ',
                      onTap: () async {
                        Navigator.pop(context);
                        await Navigator.push(
                          context,
                          MaterialPageRoute(
                            builder: (_) => ReportPage(expenses: _expenses),
                          ),
                        );
                      },
                    ),
                    _DrawerTile(
                      icon: Icons.calendar_month_outlined,
                      title: '月のレポート',
                      onTap: () async {
                        Navigator.pop(context);
                        await Navigator.push(
                          context,
                          MaterialPageRoute(
                            builder: (_) => MonthlyReportPage(
                              periodStart: currentCycleStart,
                              periodEnd: currentCycleEnd,
                            ),
                          ),
                        );
                      },
                    ),
                    const SizedBox(height: 14),
                    _DrawerSectionLabel(
                      title: 'データ管理',
                      theme: theme,
                    ),
                    _DrawerTile(
                      icon: Icons.backup_outlined,
                      title: '新規登録/ログイン',
                      subtitle: 'バックアップと復元',
                      onTap: () async {
                        Navigator.pop(context);
                        final result = await Navigator.push(
                          context,
                          MaterialPageRoute(
                            builder: (_) => const BackupRestorePage(),
                          ),
                        );
                        if (result == true) {
                          await _loadInitialData();
                        }
                      },
                    ),
                    _DrawerTile(
                      icon: Icons.restore,
                      title: '購入を復元',
                      subtitle: '以前の課金状態を確認します',
                      onTap: () async {
                        Navigator.pop(context);

                        try {
                          await Purchases.restorePurchases();
                          _hasLoadedPremium = false;
                          await _loadPremiumStatus();

                          if (!context.mounted) return;
                          ScaffoldMessenger.of(context).showSnackBar(
                            SnackBar(
                              content: Text(
                                _isPremium
                                    ? '購入を復元しました'
                                    : '復元できる購入は見つかりませんでした',
                              ),
                            ),
                          );
                        } catch (_) {
                          if (!context.mounted) return;
                          ScaffoldMessenger.of(context).showSnackBar(
                            const SnackBar(
                              content: Text('購入の復元に失敗しました'),
                            ),
                          );
                        }
                      },
                    ),
                    const SizedBox(height: 14),
                    _DrawerSectionLabel(
                      title: 'その他',
                      theme: theme,
                    ),
                    _DrawerTile(
                      icon: Icons.description_outlined,
                      title: '利用規約',
                      onTap: () {
                        Navigator.pop(context);
                      },
                    ),
                    _DrawerTile(
                      icon: Icons.privacy_tip_outlined,
                      title: 'プライバシーポリシー',
                      onTap: () {
                        Navigator.pop(context);
                      },
                    ),
                  ],
                ),
              ),
            ],
          ),
        ),
      ),
      appBar: AppBar(
        centerTitle: true,
        title: const Text('財布の余命'),
        actions: [
            if (kDebugMode)
    IconButton(
      onPressed: _openDebugTimeMenu,
      icon: const Icon(Icons.bug_report_outlined),
      tooltip: 'デバッグ時刻',
    ),
          IconButton(
            onPressed: () async {
              final result = await Navigator.push(
                context,
                MaterialPageRoute(
                  builder: (_) => const BudgetPage(),
                ),
              );

              if (result == true) {
                await _loadInitialData();
              }
            },
            icon: const Icon(Icons.savings_outlined),
            tooltip: '予算設定',
          ),
        ],
      ),
      body: Stack(
        children: [
          SafeArea(
            child: ListView(
              padding: const EdgeInsets.all(16),
              children: [
                if (_monthlyReportStatusMessage != null) ...[
                  Container(
                    width: double.infinity,
                    padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 12),
                    decoration: BoxDecoration(
                      color: const Color(0xFFF8F9FC),
                      borderRadius: BorderRadius.circular(14),
                      border: Border.all(color: const Color(0xFFE6E9F2)),
                    ),
                    child: Row(
                      children: [
                        if (_isGeneratingMonthlyReport) ...[
                          const SizedBox(
                            width: 16,
                            height: 16,
                            child: CircularProgressIndicator(strokeWidth: 2),
                          ),
                          const SizedBox(width: 10),
                        ] else ...[
                          const Icon(
                            Icons.description_outlined,
                            size: 18,
                            color: Colors.black54,
                          ),
                          const SizedBox(width: 10),
                        ],
                        Expanded(
                          child: Text(
                            _monthlyReportStatusMessage!,
                            style: theme.textTheme.bodySmall?.copyWith(
                              color: Colors.black54,
                              fontWeight: FontWeight.w600,
                            ),
                          ),
                        ),
                      ],
                    ),
                  ),
                  const SizedBox(height: 12),
                ],
                Stack(
                  clipBehavior: Clip.none,
                  children: [
                    SummaryCard(
                      isLoading: _isInitialLoading,
                      remainingBudget: remainingBudget,
                      walletLifeDays: realWalletLifeDays,
                      remainingPeriodDays: remainingPeriodDays,
                      totalBudget: _totalBudget,
                      usedAmount: usedAmount,
                      remainingTitle: remainingBudgetResult.title,
                      remainingMessage: remainingBudgetResult.message,
                      remainingSubMessage: remainingBudgetResult.subMessage,
                      cyclePeriod: cyclePeriodText,
                      dailySpendingPaceYen: dailySpendingPaceYen,
                      plannedDailyBudgetYen: plannedDailyBudgetYen,
                    ),
                    if (hasReceiptOverlay)
                      Positioned(
                        left: 0,
                        right: 0,
                        bottom: -88,
                        child: _buildSummaryReceiptOverlay(
                          theme: theme,
                          usageRate: budgetUsageRate,
                        ),
                      ),
                  ],
                ),
                SizedBox(height: 16),
                InkWell(
                  onTap: () {
                    Navigator.push(
                      context,
                      MaterialPageRoute(
                        builder: (_) => RankDetailPage(
                          rankResult: _rankResult,
                        ),
                      ),
                    );
                  },
                  borderRadius: BorderRadius.circular(22),
                  child: Container(
                    padding: const EdgeInsets.all(16),
                    decoration: BoxDecoration(
                      color: Colors.white,
                      borderRadius: BorderRadius.circular(22),
                      border: Border.all(color: const Color(0xFFF0F0F0)),
                    ),
                    child: Row(
                      children: [
                        _rankBadge(_rankResult?.rankKey, size: 52),
                        const SizedBox(width: 12),
                        Expanded(
                          child: Column(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              Row(
                                children: [
                                  Expanded(
                                    child: Text(
                                      'やりくりランク',
                                      style: theme.textTheme.titleMedium?.copyWith(
                                        fontWeight: FontWeight.w800,
                                      ),
                                    ),
                                  ),
                                  const Icon(
                                    Icons.chevron_right_rounded,
                                    color: Colors.black45,
                                  ),
                                ],
                              ),
                              const SizedBox(height: 4),
                              Text(
                                _rankResult?.rankLabel ?? 'スターター',
                                style: theme.textTheme.titleLarge?.copyWith(
                                  fontWeight: FontWeight.w800,
                                  color: Colors.black87,
                                ),
                              ),
                              const SizedBox(height: 10),
                              Wrap(
                                spacing: 8,
                                runSpacing: 8,
                                children: [
                                  Container(
                                    padding: const EdgeInsets.symmetric(
                                      horizontal: 10,
                                      vertical: 6,
                                    ),
                                    decoration: BoxDecoration(
                                      color: const Color(0xFFF8F9FC),
                                      borderRadius: BorderRadius.circular(999),
                                      border: Border.all(color: const Color(0xFFEDEDED)),
                                    ),
                                    child: Text(
                                      '${_rankResult?.streak ?? 0}ヶ月連続で予算内',
                                      style: theme.textTheme.bodySmall?.copyWith(
                                        fontWeight: FontWeight.w700,
                                        color: Colors.black87,
                                      ),
                                    ),
                                  ),
                                ],
                              ),
                            ],
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
                if (dangerCategories.isNotEmpty) ...[
                  const SizedBox(height: 16),
                  Container(
                    padding: const EdgeInsets.all(16),
                    decoration: BoxDecoration(
                      color: const Color(0xFFFFF4F1),
                      borderRadius: BorderRadius.circular(20),
                      border: Border.all(color: const Color(0xFFFFD7CC)),
                    ),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text(
                          '⚠ 危険カテゴリ',
                          style: theme.textTheme.titleMedium?.copyWith(
                            fontWeight: FontWeight.bold,
                          ),
                        ),
                        const SizedBox(height: 12),
                        if (dangerCategories.isEmpty)
                          const Text('カテゴリ予算を設定すると、危険カテゴリがここに表示されます。')
                        else
                          ...dangerCategories.map((category) {
                            return Padding(
                              padding: const EdgeInsets.only(bottom: 10),
                              child: Row(
                                children: [
                                  Text(
                                    category['badge'] as String,
                                    style: const TextStyle(fontSize: 22),
                                  ),
                                  const SizedBox(width: 10),
                                  Expanded(
                                    child: Column(
                                      crossAxisAlignment: CrossAxisAlignment.start,
                                      children: [
                                        Text(
                                          category['name'] as String,
                                          style: theme.textTheme.titleSmall?.copyWith(
                                            fontWeight: FontWeight.w700,
                                          ),
                                        ),
                                        const SizedBox(height: 2),
                                        Builder(builder: (_) {
                                          final remaining = category['remaining'] as int;
                                          final usageRate = category['usageRate'] as double;

                                          Color textColor;
                                          if (remaining < 0) {
                                            textColor = Colors.red;
                                          } else if (usageRate >= 0.9) {
                                            textColor = Colors.red;
                                          } else if (usageRate >= 0.75) {
                                            textColor = Colors.orange;
                                          } else {
                                            textColor = Colors.black87;
                                          }

                                          if (remaining < 0) {
                                            return Text(
                                              '予算オーバー ¥${_formatYen(remaining.abs())}',
                                              style: TextStyle(
                                                color: textColor,
                                                fontWeight: FontWeight.w700,
                                              ),
                                            );
                                          }

                                          return Text(
                                            '残り ¥${_formatYen(remaining)} (${(usageRate * 100).round()}%)',
                                            style: TextStyle(
                                              color: textColor,
                                              fontWeight: FontWeight.w600,
                                            ),
                                          );
                                        }),
                                      ],
                                    ),
                                  ),
                                  Builder(builder: (_) {
                                    final remaining = category['remaining'] as int;
                                    final usageRate = category['usageRate'] as double;

                                    Color color;

                                    if (remaining < 0) {
                                      color = Colors.red;
                                    } else if (usageRate >= 0.9) {
                                      color = Colors.red;
                                    } else if (usageRate >= 0.75) {
                                      color = Colors.orange;
                                    } else {
                                      color = Colors.grey;
                                    }

                                    return Icon(
                                      Icons.warning_amber_rounded,
                                      color: color,
                                    );
                                  }),
                                ],
                              ),
                            );
                          }),
                      ],
                    ),
                  ),
                ],
                const SizedBox(height: 16),
                ...roastCards.expand((card) => [
                      RoastCard(
                        title: card.title,
                        message: card.message,
                        subMessage: card.subMessage,
                      ),
                      const SizedBox(height: 12),
                    ]),
                const SizedBox(height: 16),
                Container(
                  padding: const EdgeInsets.fromLTRB(16, 14, 16, 16),
                  decoration: BoxDecoration(
                    color: Colors.white,
                    borderRadius: BorderRadius.circular(22),
                    border: Border.all(color: const Color(0xFFF0F0F0)),
                  ),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        'カテゴリ別予算',
                        style: theme.textTheme.titleLarge?.copyWith(
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                      const SizedBox(height: 4),
                      Text(
                        'カテゴリごとの進み方を確認できます',
                        style: theme.textTheme.bodySmall?.copyWith(
                          color: Colors.black54,
                          fontWeight: FontWeight.w500,
                        ),
                      ),
                      const SizedBox(height: 12),
                      Builder(
                        builder: (context) {
                          final hasOverflowCategory = categorySummaries.any(
                            (c) => (c['remaining'] as int) < 0,
                          );

                          return SizedBox(
                            height: hasOverflowCategory ? 180 : 164,
                            child: categorySummaries.isEmpty
                                ? Container(
                                    padding: const EdgeInsets.all(16),
                                    decoration: BoxDecoration(
                                      color: Colors.white,
                                      borderRadius: BorderRadius.circular(18),
                                    ),
                                    child: const Center(
                                      child: Text('カテゴリ予算を設定するとここに一覧が表示されます。'),
                                    ),
                                  )
                                : Column(
                                    children: [
                                      Expanded(
                                        child: Scrollbar(
                                          controller: _categoryScrollController,
                                          thumbVisibility: false,
                                          trackVisibility: false,
                                          radius: const Radius.circular(999),
                                          thickness: 4,
                                          scrollbarOrientation: ScrollbarOrientation.bottom,
                                          child: ListView.separated(
                                            controller: _categoryScrollController,
                                            scrollDirection: Axis.horizontal,
                                            itemCount: categorySummaries.length,
                                            separatorBuilder: (_, __) => const SizedBox(width: 10),
                                            itemBuilder: (context, index) {
                                              final category = categorySummaries[index];
                                              final budget = category['budget'] as int;
                                              final used = category['used'] as int;
                                              final progress = budget == 0
                                                  ? 0.0
                                                  : (used / budget).clamp(0.0, 1.0);

                                              return Container(
                                                width: 150,
                                                padding: const EdgeInsets.all(14),
                                                decoration: BoxDecoration(
                                                  color: Colors.white,
                                                  borderRadius: BorderRadius.circular(18),
                                                  border: Border.all(
                                                    color: const Color(0xFFEDEDED),
                                                  ),
                                                ),
                                                child: Column(
                                                  crossAxisAlignment: CrossAxisAlignment.start,
                                                  children: [
                                                    Text(
                                                      '${category['badge']} ${category['name']}',
                                                      style: theme.textTheme.titleSmall?.copyWith(
                                                        fontWeight: FontWeight.bold,
                                                      ),
                                                    ),
                                                    const SizedBox(height: 4),
                                                    Text(
                                                      '予算 ¥${_formatYen(budget)}',
                                                      style: theme.textTheme.bodySmall?.copyWith(
                                                        color: Colors.black54,
                                                        fontWeight: FontWeight.w600,
                                                      ),
                                                    ),
                                                    const SizedBox(height: 8),
                                                    Builder(builder: (_) {
                                                      final remaining = category['remaining'] as int;
                                                      final usageRate = category['usageRate'] as double;

                                                      Color textColor;
                                                      if (remaining < 0) {
                                                        textColor = Colors.red;
                                                      } else if (usageRate >= 0.9) {
                                                        textColor = Colors.red;
                                                      } else if (usageRate >= 0.75) {
                                                        textColor = Colors.orange;
                                                      } else {
                                                        textColor = Colors.black87;
                                                      }

                                                      if (remaining < 0) {
                                                        return Text(
                                                          '予算オーバー ¥${_formatYen(remaining.abs())}',
                                                          style: TextStyle(
                                                            color: textColor,
                                                            fontWeight: FontWeight.w700,
                                                          ),
                                                        );
                                                      }
                                                      return Text(
                                                        '残り ¥${_formatYen(remaining)}',
                                                        style: TextStyle(
                                                          color: textColor,
                                                          fontWeight: FontWeight.w600,
                                                        ),
                                                      );
                                                    }),
                                                    const SizedBox(height: 8),
                                                    ClipRRect(
                                                      borderRadius: BorderRadius.circular(999),
                                                      child: LinearProgressIndicator(
                                                        value: progress,
                                                        minHeight: 8,
                                                      ),
                                                    ),
                                                    const SizedBox(height: 6),
                                                    Text('${(progress * 100).round()}% 使用'),
                                                  ],
                                                ),
                                              );
                                            },
                                          ),
                                        ),
                                      ),
                                      const SizedBox(height: 6),
                                    ],
                                  ),
                          );
                        },
                      ),
                    ],
                  ),
                ),
                const SizedBox(height: 16),
                const SizedBox(height: 16),
                Container(
                  padding: const EdgeInsets.all(16),
                  decoration: BoxDecoration(
                    color: Colors.white,
                    borderRadius: BorderRadius.circular(22),
                    border: Border.all(color: const Color(0xFFF0F0F0)),
                  ),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        '分析',
                        style: theme.textTheme.titleLarge?.copyWith(
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                      const SizedBox(height: 4),
                      Text(
                        '支出の傾向や振り返りを確認できます',
                        style: theme.textTheme.bodySmall?.copyWith(
                          color: Colors.black54,
                          fontWeight: FontWeight.w500,
                        ),
                      ),
                      const SizedBox(height: 12),
                      InkWell(
                        onTap: () {
                          Navigator.push(
                            context,
                            MaterialPageRoute(
                              builder: (_) => RankingPage(
                                expenses: _expenses,
                                formatYen: _formatYen,
                              ),
                            ),
                          );
                        },
                        borderRadius: BorderRadius.circular(16),
                        child: Container(
                          width: double.infinity,
                          padding: const EdgeInsets.all(14),
                          decoration: BoxDecoration(
                            color: const Color(0xFFF8F9FC),
                            borderRadius: BorderRadius.circular(16),
                            border: Border.all(color: const Color(0xFFEDEDED)),
                          ),
                          child: Row(
                            children: [
                              Container(
                                width: 42,
                                height: 42,
                                decoration: BoxDecoration(
                                  color: const Color(0xFFFFF1EA),
                                  borderRadius: BorderRadius.circular(14),
                                ),
                                alignment: Alignment.center,
                                child: const Icon(Icons.pie_chart_outline_rounded),
                              ),
                              const SizedBox(width: 12),
                              Expanded(
                                child: Column(
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: [
                                    Text(
                                      '何に使っている？',
                                      style: theme.textTheme.titleSmall?.copyWith(
                                        fontWeight: FontWeight.w800,
                                      ),
                                    ),
                                    const SizedBox(height: 2),
                                    Text(
                                      'カテゴリ別の支出ランキングを見る',
                                      style: theme.textTheme.bodySmall?.copyWith(
                                        color: Colors.black54,
                                        fontWeight: FontWeight.w500,
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                              const SizedBox(width: 8),
                              const Icon(Icons.chevron_right_rounded),
                            ],
                          ),
                        ),
                      ),
                      const SizedBox(height: 10),
                      InkWell(
                        onTap: () {
                          Navigator.push(
                            context,
                            MaterialPageRoute(
                              builder: (_) => const MoneyUsagePage(),
                            ),
                          );
                        },
                        borderRadius: BorderRadius.circular(16),
                        child: Container(
                          width: double.infinity,
                          padding: const EdgeInsets.all(14),
                          decoration: BoxDecoration(
                            color: const Color(0xFFF8F9FC),
                            borderRadius: BorderRadius.circular(16),
                            border: Border.all(color: const Color(0xFFEDEDED)),
                          ),
                          child: Row(
                            children: [
                              Container(
                                width: 42,
                                height: 42,
                                decoration: BoxDecoration(
                                  color: const Color(0xFFEAF4FF),
                                  borderRadius: BorderRadius.circular(14),
                                ),
                                alignment: Alignment.center,
                                child: const Icon(Icons.bar_chart_rounded),
                              ),
                              const SizedBox(width: 12),
                              Expanded(
                                child: Column(
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: [
                                    Text(
                                      'どう使ってる？',
                                      style: theme.textTheme.titleSmall?.copyWith(
                                        fontWeight: FontWeight.w800,
                                      ),
                                    ),
                                    const SizedBox(height: 2),
                                    Text(
                                      '総額・カテゴリ・お店・月別で分析',
                                      style: theme.textTheme.bodySmall?.copyWith(
                                        color: Colors.black54,
                                        fontWeight: FontWeight.w500,
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                              const SizedBox(width: 8),
                              const Icon(Icons.chevron_right_rounded),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
                const SizedBox(height: 16),
                Text(
                  'タイムライン',
                  style: theme.textTheme.titleLarge?.copyWith(
                    fontWeight: FontWeight.bold,
                  ),
                ),
                const SizedBox(height: 12),
                if (currentCycleExpenses.isEmpty) ...[
                  Container(
                    padding: const EdgeInsets.all(16),
                    decoration: BoxDecoration(
                      color: Colors.white,
                      borderRadius: BorderRadius.circular(20),
                    ),
                    child: const Text('まだ支出がありません。最初の支出を追加してみましょう。'),
                  ),
                  const SizedBox(height: 90),
                ] else ...[
                  ...currentCycleExpenses.take(10).expand((expense) => [
                        Dismissible(
                          key: ValueKey(expense.id),
                          direction: DismissDirection.endToStart,
                          background: Container(
                            decoration: BoxDecoration(
                              color: const Color(0xFFFFF1F1),
                              borderRadius: BorderRadius.circular(18),
                            ),
                          ),
                          secondaryBackground: Container(
                            alignment: Alignment.centerRight,
                            padding: const EdgeInsets.symmetric(horizontal: 20),
                            decoration: BoxDecoration(
                              color: const Color(0xFFFFE1E1),
                              borderRadius: BorderRadius.circular(18),
                            ),
                            child: const Icon(
                              Icons.delete_outline,
                              color: Color(0xFFD64B4B),
                              size: 28,
                            ),
                          ),
                          confirmDismiss: (_) async {
                            final deleted = await _deleteExpense(expense);
                            return deleted;
                          },
                          child: TimelineItem(
                            title: expense.storeName,
                            subtitle: expense.category,
                            amount: '¥${_formatYen(expense.amount)}',
                            icon: _iconForCategory(expense.category),
                            date: _formatTimelineDate(expense.createdAt),
                            onEdit: () async {
                              await _editExpense(expense);
                            },
                            onDelete: () async {
                              await _deleteExpense(expense);
                            },
                          ),
                        ),
                        if (expense.futureLogMessage != null) ...[
                          const SizedBox(height: 10),
                          FutureLogItem(message: expense.futureLogMessage!),
                        ],
                        const SizedBox(height: 10),
                      ]),
                  Center(
                    child: TextButton(
                      onPressed: _openFullTimeline,
                      child: const Text('一覧へ'),
                    ),
                  ),
                  const SizedBox(height: 70),
                ]
              ],
            ),
          ),
          if (hasFullScreenReceiptOverlay)
            Positioned.fill(
              child: _buildFullScreenReceiptOverlay(
                usageRate: budgetUsageRate,
              ),
            ),
        ],
      ),
      floatingActionButton: FloatingActionButton.extended(
        onPressed: () async {
          final result = await Navigator.push(
            context,
            MaterialPageRoute(
              builder: (_) => const AddExpensePage(),
            ),
          );

          if (result == true) {
            await _loadInitialData();
          }
        },
        label: const Text('支出を追加'),
        icon: const Icon(Icons.add),
      ),
    );
  }

  Future<Expense?> _editExpense(Expense expense) async {
  final result = await Navigator.push(
    context,
    MaterialPageRoute(
      builder: (_) => AddExpensePage(initialExpense: expense),
    ),
  );

  if (result == true) {
    await _loadInitialData();

    for (final item in _expenses) {
      if (item.id == expense.id) return item;
    }
  }

  return null;
}

Future<bool> _deleteExpense(Expense expense) async {
  final shouldDelete = await showDialog<bool>(
    context: context,
    builder: (dialogContext) {
      return AlertDialog(
        title: const Text('支出を削除しますか？'),
        content: Text('${expense.storeName} の支出を削除します。'),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(dialogContext, false),
            child: const Text('キャンセル'),
          ),
          TextButton(
            onPressed: () => Navigator.pop(dialogContext, true),
            child: const Text('削除'),
          ),
        ],
      );
    },
  );

  if (shouldDelete != true) return false;

  await IsarService.deleteExpense(expense.id);
  await flutterLocalNotificationsPlugin.cancel(id: expense.id);
  if (_isPremium) {
    await ExpenseSyncService.deleteExpense(expense.id);
  }
  await _loadInitialData();
  return true;
}


void _openFullTimeline() {
  Navigator.push(
    context,
    MaterialPageRoute(
      builder: (_) => TimelinePage(
        expenses: _currentCycleExpensesCache,
        formatYen: _formatYen,
        categoryLabel: (category) => category,
        iconForCategory: _iconForCategory,
        formatTimelineDate: _formatTimelineDate,
        onEditExpense: _editExpense,
        onDeleteExpense: _deleteExpense,
      ),
    ),
  );
}


  Future<void> _autoGenerateMonthlyReportIfNeeded() async {
  final budgetSetting = await IsarService.getBudgetSetting();
  if (budgetSetting == null) return;
  if (budgetSetting.totalBudget <= 0) return;

  final cycleStartDay = budgetSetting.cycleStartDay.clamp(1, 28);
  final now = getNow();
  final baseStart = now.day >= cycleStartDay
      ? DateTime(now.year, now.month, cycleStartDay)
      : DateTime(now.year, now.month - 1, cycleStartDay);

  final currentCycleStart = DateTime(
    baseStart.year,
    baseStart.month + _cycleOffsetMonths,
    baseStart.day,
  );

  final currentId = budgetSetting.currentBudgetHistoryLocalId;
  if (currentId == null) return;

  final currentHistory = await IsarService.getBudgetHistoryById(currentId);
  if (currentHistory == null) return;

  final histories = await IsarService.getBudgetHistories();
  final sorted = [...histories]..sort((a, b) => a.startDate.compareTo(b.startDate));
  final currentIndex = sorted.indexWhere((h) => h.id == currentId);

  if (currentIndex <= 0) {
    if (!mounted) return;
    setState(() {
      _isGeneratingMonthlyReport = false;
      _monthlyReportStatusMessage = null;
    });
    return;
  }

  final previousHistory = sorted[currentIndex - 1];
  final existingReport = await MonthlyReportService.getReportForHistoryLocalId(
    localId: previousHistory.id,
  );

  if (existingReport != null) {
    if (!mounted) return;
    setState(() {
      _isGeneratingMonthlyReport = false;
      _monthlyReportStatusMessage = null;
    });
    return;
  }

  if (mounted) {
    setState(() {
      _isGeneratingMonthlyReport = true;
      _monthlyReportStatusMessage = '月のレポートを作成しています...';
    });
  }

  try {
    final didGenerate = await MonthlyReportService.autoGenerateIfNeeded(
      now: now,
      currentCycleStart: currentCycleStart,
      cycleStartDay: cycleStartDay,
    );

    if (!mounted) return;

    if (!didGenerate) {
      setState(() {
        _isGeneratingMonthlyReport = false;
        _monthlyReportStatusMessage = null;
      });
      return;
    }

    setState(() {
      _isGeneratingMonthlyReport = false;
      _monthlyReportStatusMessage = '月のレポートを作成しました';
    });

    Future.delayed(const Duration(seconds: 3), () {
      if (!mounted) return;
      setState(() {
        _monthlyReportStatusMessage = null;
      });
    });
  } catch (e) {
    debugPrint('[MonthlyReport] auto generate skipped: $e');
    if (!mounted) return;
    setState(() {
      _isGeneratingMonthlyReport = false;
      _monthlyReportStatusMessage = null;
    });
  }
}

  Future<List<({String title, String message, String subMessage})>>
      _buildRoastCards({
    required List<Expense> currentCycleExpenses,
    required int totalBudget,
    required int usedAmount,
    required DateTime start,
    required DateTime endInclusive,
    required List<Map<String, dynamic>> dangerCategories,
  }) async {
    final latestCategoryTagUsedAmounts = <ExpenseJudgeTag, int>{};
    if (currentCycleExpenses.isNotEmpty) {
      final latestCategory = currentCycleExpenses.first.category;
      final categoryExpenses = currentCycleExpenses
          .where((expense) => expense.category == latestCategory)
          .toList();

      for (final expense in categoryExpenses) {
        final judge = ExpenseJudgeService.judge(
          expense: expense,
          totalBudget: totalBudget,
        );

        for (final tag in judge.tags) {
          latestCategoryTagUsedAmounts[tag] =
              (latestCategoryTagUsedAmounts[tag] ?? 0) + expense.amount;
        }
      }
    }

    final categoryCountMap = <String, int>{};
    final categoryAmountMap = <String, int>{};

    for (final expense in currentCycleExpenses) {
      final category = expense.category;
      categoryCountMap[category] = (categoryCountMap[category] ?? 0) + 1;
      categoryAmountMap[category] =
          (categoryAmountMap[category] ?? 0) + expense.amount;
    }

    final latestCategoryBudget = currentCycleExpenses.isEmpty
        ? 0
        : (() {
            final latestCategory = currentCycleExpenses.first.category;
            final matchedCategory = _budgetSetting?.categories
                .where((category) => category.name == latestCategory)
                .toList();
            if (matchedCategory == null || matchedCategory.isEmpty) return 0;
            return matchedCategory.first.budget;
          })();

    final latestCategoryUsed = currentCycleExpenses.isEmpty
        ? 0
        : (() {
            final latestCategory = currentCycleExpenses.first.category;
            return currentCycleExpenses
                .where((expense) => expense.category == latestCategory)
                .fold<int>(0, (sum, expense) => sum + expense.amount);
          })();

    final roastResult = await RoastService.build(
      totalBudget: totalBudget,
      usedAmount: usedAmount,
      expenses: currentCycleExpenses,
      dangerCategories: dangerCategories.take(3).toList(),
      latestCategoryBudget: latestCategoryBudget,
      latestCategoryUsed: latestCategoryUsed,
      cycleStart: start,
      cycleEnd: endInclusive,
      latestCategoryTagUsedAmounts: latestCategoryTagUsedAmounts,
    );

    final roastCards = <({String title, String message, String subMessage})>[];

    final subLines = roastResult.subMessage
        .split('\n')
        .map((text) => text.trim())
        .where((text) => text.isNotEmpty)
        .toList();

    final hasLayeredRoast = subLines.length >= 3;

    if (hasLayeredRoast) {
      final monthlySubMessage = subLines.isNotEmpty ? subLines.first : '';
      final latestMessage = subLines.length >= 2 ? subLines[1] : '';
      final latestSubMessage =
          subLines.length >= 3 ? subLines.sublist(2).join('\n') : '';

      roastCards.add((
        title: roastResult.title,
        message: roastResult.message,
        subMessage: monthlySubMessage,
      ));

      roastCards.add((
        title: '財布からもうひとこと',
        message: latestMessage,
        subMessage: latestSubMessage,
      ));
    } else {
      roastCards.add((
        title: roastResult.title,
        message: roastResult.message,
        subMessage: roastResult.subMessage,
      ));
    }

    return roastCards;
  }
  }

  // Drawer section label widget
class _DrawerSectionLabel extends StatelessWidget {
  const _DrawerSectionLabel({
    required this.title,
    required this.theme,
  });

  final String title;
  final ThemeData theme;

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.fromLTRB(8, 0, 8, 6),
      child: Text(
        title,
        style: theme.textTheme.bodySmall?.copyWith(
          color: Colors.black54,
          fontWeight: FontWeight.w700,
        ),
      ),
    );
  }
}

class _DrawerTile extends StatelessWidget {
  const _DrawerTile({
    required this.icon,
    required this.title,
    this.subtitle,
    required this.onTap,
  });

  final IconData icon;
  final String title;
  final String? subtitle;
  final VoidCallback onTap;

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);

    return Padding(
      padding: const EdgeInsets.only(bottom: 8),
      child: Material(
        color: const Color(0xFFF8F9FC),
        borderRadius: BorderRadius.circular(18),
        child: ListTile(
          onTap: onTap,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(18),
          ),
          contentPadding: const EdgeInsets.symmetric(
            horizontal: 14,
            vertical: 4,
          ),
          leading: Container(
            width: 40,
            height: 40,
            decoration: BoxDecoration(
              color: Colors.white,
              borderRadius: BorderRadius.circular(12),
            ),
            alignment: Alignment.center,
            child: Icon(icon, color: Colors.black87),
          ),
          title: Text(
            title,
            style: theme.textTheme.titleSmall?.copyWith(
              fontWeight: FontWeight.w700,
            ),
          ),
          subtitle: subtitle == null
              ? null
              : Padding(
                  padding: const EdgeInsets.only(top: 2),
                  child: Text(
                    subtitle!,
                    style: theme.textTheme.bodySmall?.copyWith(
                      color: Colors.black54,
                      height: 1.35,
                    ),
                  ),
                ),
          trailing: const Icon(
            Icons.chevron_right_rounded,
            color: Colors.black38,
          ),
        ),
      ),
    );
  }
}


class _ReceiptDecorationItem {
  const _ReceiptDecorationItem({
    this.left,
    this.right,
    required this.top,
    required this.width,
    required this.rotation,
    required this.opacity,
  });

  final double? left;
  final double? right;
  final double top;
  final double width;
  final double rotation;
  final double opacity;
}

class _ReceiptDecorationCard extends StatelessWidget {
  const _ReceiptDecorationCard({
    required this.width,
  });

  final double width;

  @override
  Widget build(BuildContext context) {
    return Container(
      width: width,
      height: width * 1.42,
      padding: const EdgeInsets.fromLTRB(10, 12, 10, 10),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(10),
        border: Border.all(color: const Color(0xFFE9E9E9)),
        boxShadow: const [
          BoxShadow(
            color: Color(0x14000000),
            blurRadius: 10,
            offset: Offset(0, 4),
          ),
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Container(
            width: 36,
            height: 6,
            decoration: BoxDecoration(
              color: const Color(0xFFFFE5DB),
              borderRadius: BorderRadius.circular(999),
            ),
          ),
          const SizedBox(height: 10),
          ...List.generate(
            5,
            (index) => Padding(
              padding: const EdgeInsets.only(bottom: 6),
              child: Container(
                width: double.infinity,
                height: 4,
                decoration: BoxDecoration(
                  color: index.isEven
                      ? const Color(0xFFE8ECF2)
                      : const Color(0xFFF1F3F6),
                  borderRadius: BorderRadius.circular(999),
                ),
              ),
            ),
          ),
          const Spacer(),
          Align(
            alignment: Alignment.centerRight,
            child: Container(
              width: 26,
              height: 6,
              decoration: BoxDecoration(
                color: const Color(0xFFFFD2C4),
                borderRadius: BorderRadius.circular(999),
              ),
            ),
          ),
        ],
      ),
    );
  }
}