import 'package:flutter/material.dart';
import 'package:saiyome/screens/budget_page.dart';
import 'package:saiyome/screens/monthly_report_page.dart';
import 'package:saiyome/screens/report_page.dart';
import 'package:saiyome/screens/backup_restore_page.dart';
import 'package:saiyome/screens/premium_page.dart';
import 'package:purchases_flutter/purchases_flutter.dart';
import 'package:saiyome/widgets/future_log_item.dart';
import 'package:saiyome/widgets/roast_card.dart';
import 'package:saiyome/widgets/summary_card.dart';
import 'package:saiyome/widgets/timeline_item.dart';
import 'package:saiyome/screens/add_expense_page.dart';
import 'package:saiyome/models/expense.dart';
import 'package:saiyome/models/budget_history.dart';
import 'package:saiyome/models/isar_service.dart';
import 'package:intl/intl.dart';
import 'package:saiyome/services/roast_service.dart';
import 'package:saiyome/services/expense_judge_service.dart';
import 'package:saiyome/services/remaining_budget_service.dart';
import 'package:saiyome/screens/timeline_page.dart';
import 'package:saiyome/screens/ranking_page.dart';
import 'package:saiyome/screens/money_usage_page.dart';
import 'package:saiyome/screens/rank_detail_page.dart';
import 'package:saiyome/services/rank_service.dart';
import 'package:saiyome/services/budget_history_service.dart';
import 'package:saiyome/services/monthly_report_service.dart';
import 'package:saiyome/services/expense_sync_service.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:flutter/foundation.dart';
import 'package:saiyome/utils/time_provider.dart';

class HomePage extends StatefulWidget {
  const HomePage({super.key});

  @override
  State<HomePage> createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  List<Expense> _expenses = [];
  BudgetSetting? _budgetSetting;
  RankResult? _rankResult;
  bool _isPremium = false;
  bool _hasLoadedPremium = false;
  bool _isInitialLoading = true;
  List<Expense> _currentCycleExpensesCache = [];
  int _usedAmountCache = 0;
  int _remainingBudgetCache = 0;
  int _realWalletLifeDaysCache = 0;
  int _dailySpendingPaceYenCache = 0;
  int _plannedDailyBudgetYenCache = 0;
  List<Map<String, dynamic>> _categorySummariesCache = [];
  List<Map<String, dynamic>> _dangerCategoriesCache = [];
  List<({String title, String message, String subMessage})> _roastCardsCache = [];
  RemainingBudgetResult _remainingBudgetResultCache = const RemainingBudgetResult(
    title: '',
    message: '',
    subMessage: '',
  );
  bool _hasAutoGeneratedMonthlyReport = false;
  bool _isGeneratingMonthlyReport = false;
  String? _monthlyReportStatusMessage;
  BudgetHistory? _currentBudgetHistory;

  User? get _currentUser => Supabase.instance.client.auth.currentUser;

  bool get _isLoggedIn {
    final user = _currentUser;
    return user != null && !user.isAnonymous;
  }

  int _cycleOffsetMonths = 0;
  final ScrollController _categoryScrollController = ScrollController();

@override
void initState() {
  super.initState();
  _initPage();
}

Future<void> _initPage() async {
  await ensureDebugTimeLoaded();
  await _loadInitialData();
}

  @override
  void dispose() {
    _categoryScrollController.dispose();
    super.dispose();
  }

Future<void> _loadInitialData() async {
  if (mounted) {
    setState(() {
      _isInitialLoading = true;
    });
  }

  await _syncBudgetHistoryIfNeeded();
  await _loadBudgetSetting();
  await _loadPremiumStatus();

  if (_isPremium && !_hasAutoGeneratedMonthlyReport) {
    await _autoGenerateMonthlyReportIfNeeded();
    _hasAutoGeneratedMonthlyReport = true;
  }

  await Future.wait([
    _loadExpenses(),
    _loadRankData(),
  ]);

  if (mounted) {
    setState(() {
      _isInitialLoading = false;
    });
  }
}

Future<void> _syncBudgetHistoryIfNeeded() async {
  final budgetSetting = await IsarService.getBudgetSetting();
  if (budgetSetting == null) return;
  if (budgetSetting.totalBudget <= 0) return;

  await BudgetHistoryService.syncIfNeeded(
    cycleStartDay: budgetSetting.cycleStartDay,
    totalBudget: budgetSetting.totalBudget,
  );

  _currentBudgetHistory = null;
}

  Future<void> _recomputeDerivedCaches() async {
    final start = _currentCycleStart;
    final endExclusive = _currentCycleEndExclusive;
    final endInclusive = _currentCycleEnd;

    final currentCycleExpenses = _expenses.where((expense) {
      final createdAt = expense.createdAt;
      return !createdAt.isBefore(start) && createdAt.isBefore(endExclusive);
    }).toList();

    final usedAmount = currentCycleExpenses.fold<int>(
      0,
      (sum, expense) => sum + expense.amount,
    );

    final totalBudget = _totalBudget;
    final remainingBudgetRaw = totalBudget - usedAmount;
    final remainingBudget = remainingBudgetRaw < 0 ? 0 : remainingBudgetRaw;

    int realWalletLifeDays = 0;
    if (_cycleOffsetMonths == 0 && totalBudget > 0 && remainingBudget > 0) {
      final totalCycleDays = endInclusive.difference(start).inDays;
      if (totalCycleDays > 0) {
        final plannedDailyBudget = totalBudget / totalCycleDays;
        if (plannedDailyBudget > 0) {
          realWalletLifeDays =
              (remainingBudget / plannedDailyBudget).ceil().clamp(1, 999);
        }
      }
    }

    int dailySpendingPaceYen = 0;
    if (_cycleOffsetMonths == 0 && usedAmount > 0) {
      // final now = DateTime.now();
      final now = getNow();
      final today = DateTime(now.year, now.month, now.day);
      final normalizedCycleStart = DateTime(start.year, start.month, start.day);
      final elapsedDays = today.difference(normalizedCycleStart).inDays + 1;
      if (elapsedDays > 0) {
        dailySpendingPaceYen = (usedAmount / elapsedDays).round();
      }
    }

    int plannedDailyBudgetYen = 0;
    if (_cycleOffsetMonths == 0 && totalBudget > 0) {
      final totalCycleDays = endInclusive.difference(start).inDays;
      if (totalCycleDays > 0) {
        plannedDailyBudgetYen = (totalBudget / totalCycleDays).round();
      }
    }

    final categories = _budgetSetting?.categories ?? [];
    final categorySummaries = categories.map((category) {
      final used = currentCycleExpenses
          .where((expense) => expense.category == category.name)
          .fold<int>(0, (sum, expense) => sum + expense.amount);
      final remaining = category.budget - used;
      final usageRate = category.budget == 0 ? 0.0 : used / category.budget;

      return {
        'name': category.name,
        'badge': category.badge,
        'budget': category.budget,
        'used': used,
        'remaining': remaining,
        'usageRate': usageRate,
      };
    }).toList();

    final dangerCategories = categorySummaries.where((category) {
      final budget = category['budget'] as int;
      if (budget == 0) return false;

      final usageRate = category['usageRate'] as double;
      final remaining = category['remaining'] as int;
      return remaining < 0 || usageRate >= 0.75;
    }).toList();

    dangerCategories.sort((a, b) {
      final aRate = a['usageRate'] as double;
      final bRate = b['usageRate'] as double;
      return bRate.compareTo(aRate);
    });

    final roastCards = await _buildRoastCards(
      currentCycleExpenses: currentCycleExpenses,
      totalBudget: totalBudget,
      usedAmount: usedAmount,
      start: start,
      endInclusive: endInclusive,
      dangerCategories: dangerCategories,
    );

    final remainingBudgetResult = RemainingBudgetService.build(
      totalBudget: totalBudget,
      usedAmount: usedAmount,
      cycleStart: start,
      cycleEnd: endInclusive,
    );

    if (!mounted) return;

    setState(() {
    _currentCycleExpensesCache = currentCycleExpenses;
    _usedAmountCache = usedAmount;
    _remainingBudgetCache = remainingBudget;
    _realWalletLifeDaysCache = realWalletLifeDays;
    _dailySpendingPaceYenCache = dailySpendingPaceYen;
    _plannedDailyBudgetYenCache = plannedDailyBudgetYen;
    _categorySummariesCache = categorySummaries;
    _dangerCategoriesCache = dangerCategories.take(3).toList();
    _roastCardsCache = roastCards;
    _remainingBudgetResultCache = remainingBudgetResult;
    });
  }

  Future<void> _loadExpenses() async {
    final expenses = await IsarService.getExpenses();
    if (!mounted) return;

    setState(() {
      _expenses = expenses;
    });

    await _recomputeDerivedCaches();
  }

  Future<void> _loadBudgetSetting() async {
    final budgetSetting = await IsarService.getBudgetSetting();
    if (budgetSetting == null) return;

    final histories = await IsarService.getBudgetHistories();
    final now = getNow();

    BudgetHistory? currentHistory;
    for (final history in histories) {
      if (!now.isBefore(history.startDate) && now.isBefore(history.endDate)) {
        currentHistory = history;
        break;
      }
    }

    if (!mounted) return;

    setState(() {
      _budgetSetting = budgetSetting;
      _currentBudgetHistory = currentHistory;
    });

    await _recomputeDerivedCaches();
  }

  Future<void> _loadRankData() async {
  final histories = await IsarService.getBudgetHistories();
  if (!mounted) return;
  setState(() {
    _rankResult = RankService.calculate(histories);
  });
}

  Future<void> _loadPremiumStatus() async {
    if (_hasLoadedPremium) return;

    try {
      final customerInfo = await Purchases.getCustomerInfo();
      if (!mounted) return;
      setState(() {
        _isPremium = customerInfo.entitlements.active.containsKey('premium');
        _hasLoadedPremium = true;
      });
    } catch (_) {
      if (!mounted) return;
      setState(() {
        _isPremium = false;
        _hasLoadedPremium = true;
      });
    }
  }

  Future<void> _generateMonthlyReportForTest() async {
    if (mounted) {
      setState(() {
        _isGeneratingMonthlyReport = true;
        _monthlyReportStatusMessage = 'レポート作成中です...';
      });
    }

    try {
      final response = await Supabase.instance.client.functions.invoke(
        'generate-monthly-report',
        body: {
          'cycleStart': _currentCycleStart.toIso8601String(),
          'cycleEnd': _currentCycleEnd.toIso8601String(),
        },
      );

      if (!mounted) return;
      setState(() {
        _isGeneratingMonthlyReport = false;
        _monthlyReportStatusMessage = 'レポートを作成しました';
      });
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text('月レポート生成を実行しました: ${response.data}'),
        ),
      );
    } catch (e) {
      if (!mounted) return;
      setState(() {
        _isGeneratingMonthlyReport = false;
        _monthlyReportStatusMessage = 'レポート作成に失敗しました';
      });
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text('月レポート生成に失敗しました: $e'),
        ),
      );
    }
  }

  IconData _iconForCategory(String category) {
    switch (category) {
      case 'カフェ':
        return Icons.local_cafe_outlined;
      case 'コンビニ':
        return Icons.storefront_outlined;
      case '外食':
        return Icons.restaurant_outlined;
      case '日用品':
        return Icons.shopping_bag_outlined;
      case '趣味':
        return Icons.sports_esports_outlined;
      case '食費':
      default:
        return Icons.receipt_long_outlined;
    }
  }


  int get _cycleStartDay {
    final day = _budgetSetting?.cycleStartDay ?? 1;
    return day.clamp(1, 28);
  }

({DateTime start, DateTime endExclusive}) _resolvedCurrentCycleRange() {
  if (_cycleOffsetMonths == 0 && _currentBudgetHistory != null) {
    return (
      start: _currentBudgetHistory!.startDate,
      endExclusive: _currentBudgetHistory!.endDate,
    );
  }

  final now = getNow();
  final startDay = _cycleStartDay.clamp(1, 28);

  final baseStart = now.day >= startDay
      ? DateTime(now.year, now.month, startDay)
      : DateTime(now.year, now.month - 1, startDay);

  final start = DateTime(
    baseStart.year,
    baseStart.month + _cycleOffsetMonths,
    baseStart.day,
  );
  final endExclusive = DateTime(start.year, start.month + 1, startDay);

  return (start: start, endExclusive: endExclusive);
}

DateTime get _currentCycleStart => _resolvedCurrentCycleRange().start;

DateTime get _currentCycleEndExclusive =>
    _resolvedCurrentCycleRange().endExclusive;

DateTime get _currentCycleEnd {
  final endExclusive = _currentCycleEndExclusive;
  return endExclusive.subtract(const Duration(days: 1));
}


  int get _totalBudget {
    return _budgetSetting?.totalBudget ?? 0;
  }


  int _remainingPeriodDays() {
  // final now = DateTime.now();
  final now = getNow();
  final today = DateTime(now.year, now.month, now.day);
  final end = DateTime(
    _currentCycleEnd.year,
    _currentCycleEnd.month,
    _currentCycleEnd.day,
  );

  final diff = end.difference(today).inDays;
  return diff < 0 ? 0 : diff;
}


  String _formatYen(int value) {
    final formatter = NumberFormat('#,###');
    return formatter.format(value);
  }

String _formatTimelineDate(DateTime date) {
  // final now = DateTime.now();
  final now = getNow();
  final today = DateTime(now.year, now.month, now.day);
  final target = DateTime(date.year, date.month, date.day);

  final diff = today.difference(target).inDays;

  if (diff == 0) return '今日';
  if (diff == 1) return '昨日';

  return DateFormat('M/d').format(date);
}

String _formatCyclePeriod() {
  final start = _currentCycleStart;
  final end = _currentCycleEnd;
  return '${start.month}/${start.day} 〜 ${end.month}/${end.day}';
}

Widget _rankBadge(String? rankKey, {double size = 52}) {
  Color color;

  switch (rankKey) {
    case 'diamond':
      color = const Color(0xFF8B5CF6);
      break;
    case 'platinum':
      color = const Color(0xFF94A3B8);
      break;
    case 'gold':
      color = const Color(0xFFF5B700);
      break;
    case 'silver':
      color = const Color(0xFFB8C2CC);
      break;
    case 'bronze':
      color = const Color(0xFFC47A44);
      break;
    default:
      color = const Color(0xFFA3A3A3);
  }

  return Container(
    width: size,
    height: size,
    alignment: Alignment.center,
    decoration: BoxDecoration(
      color: color,
      shape: BoxShape.circle,
      border: Border.all(color: Colors.black.withOpacity(0.05)),
      boxShadow: [
        BoxShadow(
          color: Colors.black.withOpacity(0.06),
          blurRadius: 10,
          offset: const Offset(0, 4),
        ),
      ],
    ),
    child: Icon(
      Icons.auto_graph_rounded,
      color: Colors.white,
      size: size * 0.42,
    ),
  );
}

Future<void> _shiftDebugNow(Duration delta) async {
  final base = getNow();
  await setDebugNow(base.add(delta));
  if (!mounted) return;
  await _loadInitialData();
}

Future<void> _resetDebugNow() async {
  await clearDebugNow();
  if (!mounted) return;
  await _loadInitialData();
}

Future<void> _openDebugTimeMenu() async {
  if (!kDebugMode) return;

  await showModalBottomSheet<void>(
    context: context,
    isScrollControlled: true,
    builder: (sheetContext) {
      final now = getNow();
      return SafeArea(
        child: FractionallySizedBox(
          heightFactor: 0.72,
          child: Column(
            mainAxisSize: MainAxisSize.max,
            children: [
              const SizedBox(height: 8),
              Container(
                width: 42,
                height: 4,
                decoration: BoxDecoration(
                  color: const Color(0xFFD6D6D6),
                  borderRadius: BorderRadius.circular(999),
                ),
              ),
              ListTile(
                title: const Text('デバッグ時刻'),
                subtitle: Text(DateFormat('yyyy/MM/dd').format(now)),
              ),
              Expanded(
                child: ListView(
                  children: [
                    ListTile(
                      leading: const Icon(Icons.remove),
                      title: const Text('-1日'),
                      onTap: () async {
                        Navigator.pop(sheetContext);
                        await _shiftDebugNow(const Duration(days: -1));
                      },
                    ),
                    ListTile(
                      leading: const Icon(Icons.add),
                      title: const Text('+1日'),
                      onTap: () async {
                        Navigator.pop(sheetContext);
                        await _shiftDebugNow(const Duration(days: 1));
                      },
                    ),
                    ListTile(
                      leading: const Icon(Icons.remove),
                      title: const Text('-7日'),
                      onTap: () async {
                        Navigator.pop(sheetContext);
                        await _shiftDebugNow(const Duration(days: -7));
                      },
                    ),
                    ListTile(
                      leading: const Icon(Icons.add),
                      title: const Text('+7日'),
                      onTap: () async {
                        Navigator.pop(sheetContext);
                        await _shiftDebugNow(const Duration(days: 7));
                      },
                    ),
                    ListTile(
                      leading: const Icon(Icons.remove),
                      title: const Text('-30日'),
                      onTap: () async {
                        Navigator.pop(sheetContext);
                        await _shiftDebugNow(const Duration(days: -30));
                      },
                    ),
                    ListTile(
                      leading: const Icon(Icons.add),
                      title: const Text('+30日'),
                      onTap: () async {
                        Navigator.pop(sheetContext);
                        await _shiftDebugNow(const Duration(days: 30));
                      },
                    ),
                    ListTile(
                      leading: const Icon(Icons.refresh),
                      title: const Text('現在に戻す'),
                      onTap: () async {
                        Navigator.pop(sheetContext);
                        await _resetDebugNow();
                      },
                    ),
                  ],
                ),
              ),
              const SizedBox(height: 12),
            ],
          ),
        ),
      );
    },
  );
}

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final currentUser = _currentUser;
    final isLoggedIn = _isLoggedIn;
    final currentCycleStart = _currentCycleStart;
    final currentCycleEnd = _currentCycleEnd;
    final currentCycleExpenses = _currentCycleExpensesCache;
    final usedAmount = _usedAmountCache;
    final remainingBudget = _remainingBudgetCache;
    final realWalletLifeDays = _realWalletLifeDaysCache;
    final remainingPeriodDays = _remainingPeriodDays();
    final remainingBudgetResult = _remainingBudgetResultCache;
    final dailySpendingPaceYen = _dailySpendingPaceYenCache;
    final plannedDailyBudgetYen = _plannedDailyBudgetYenCache;
    final cyclePeriodText = _formatCyclePeriod();
    final dangerCategories = _dangerCategoriesCache;
    final roastCards = _roastCardsCache;
    final categorySummaries = _categorySummariesCache;

    return Scaffold(
      drawer: Drawer(
        child: SafeArea(
          child: ListView(
            padding: EdgeInsets.zero,
            children: [
              if (kDebugMode) ...[
  Container(
    width: double.infinity,
    padding: const EdgeInsets.all(12),
    decoration: BoxDecoration(
      color: const Color(0xFFF8F9FC),
      borderRadius: BorderRadius.circular(14),
      border: Border.all(color: const Color(0xFFE6E9F2)),
    ),
    child: Text(
      'デバッグ時刻: ${DateFormat('yyyy/MM/dd').format(getNow())}',
      style: theme.textTheme.bodySmall?.copyWith(
        fontWeight: FontWeight.w700,
        color: Colors.black87,
      ),
    ),
  ),
  const SizedBox(height: 12),
],
              const SizedBox(height: 12),
              ListTile(
                leading: Icon(
                  isLoggedIn ? Icons.verified_user_outlined : Icons.person_outline,
                ),
                title: Text(isLoggedIn ? 'ログイン中' : '未ログイン'),
                subtitle: Text(
                  isLoggedIn
                      ? (currentUser?.email?.isNotEmpty == true
                          ? currentUser!.email!
                          : 'Apple / Google アカウントで利用中')
                      : 'アカウント登録・ログインで引き継ぎできます',
                ),
                onTap: () async {
                  Navigator.pop(context);
                  final result = await Navigator.push(
                    context,
                    MaterialPageRoute(
                      builder: (_) => const BackupRestorePage(),
                    ),
                  );
                  if (result == true) {
                    await _loadInitialData();
                  }
                },
              ),
              const Divider(),
              ListTile(
                leading: const Icon(Icons.workspace_premium_rounded),
                title: Text(_isPremium ? 'プレミアム利用中' : 'プレミアム'),
                subtitle: Text(
                  _isPremium
                      ? 'すべてのプレミアム機能が使えます'
                      : 'レポート・バッヂ・バックアップ・レシート機能を解放',
                ),
                onTap: () async {
                  Navigator.pop(context);
                  final result = await Navigator.push(
                    context,
                    MaterialPageRoute(
                      builder: (_) => const PremiumPage(),
                    ),
                  );
                  if (result == true) {
                    await _loadPremiumStatus();
                  }
                },
              ),
              ListTile(
                leading: const Icon(Icons.credit_card_outlined),
                title: const Text('クレカ連携…？'),
                subtitle: const Text('自動連携について'),
                onTap: () async {
                  Navigator.pop(context);

                  final confirm = await showDialog<bool>(
                    context: context,
                    builder: (dialogContext) {
                      return AlertDialog(
                        title: const Text('本当に連携しますか？'),
                        content: const Text('クレジットカードと連携して、自動で記録しますか？'),
                        actions: [
                          TextButton(
                            onPressed: () => Navigator.pop(dialogContext, false),
                            child: const Text('やめる'),
                          ),
                          TextButton(
                            onPressed: () => Navigator.pop(dialogContext, true),
                            child: const Text('はい'),
                          ),
                        ],
                      );
                    },
                  );

                  if (confirm != true) return;

                  if (!context.mounted) return;

                  await showDialog(
                    context: context,
                    builder: (dialogContext) {
                      return AlertDialog(
                        title: const Text('クレカ連携、ありません笑'),
                        content: const Text(
                          'このアプリは、あえて自動連携をしていません。\n\n'
                          '入力するひと手間が、使いすぎへの気づきにつながるからです。\n\n'
                          '少し面倒ですが、いっしょに財布と向き合っていきましょう。\n\n'
                          '👉 まずは今日の支出を1つだけ記録してみましょう。'
                        ),
                        actions: [
                          TextButton(
                            onPressed: () => Navigator.pop(dialogContext),
                            child: const Text('OK'),
                          ),
                        ],
                      );
                    },
                  );
                },
              ),
              ListTile(
                leading: const Icon(Icons.savings_outlined),
                title: const Text('予算設定'),
                onTap: () async {
                  Navigator.pop(context);
                  final result = await Navigator.push(
                    context,
                    MaterialPageRoute(
                      builder: (_) => const BudgetPage(),
                    ),
                  );
                  if (result == true) {
                    await _loadInitialData();
                  }
                },
              ),
              ListTile(
                leading: const Icon(Icons.summarize_outlined),
                title: const Text('今週のまとめ'),
                onTap: () async {
                  Navigator.pop(context);
                  await Navigator.push(
                    context,
                    MaterialPageRoute(
                      builder: (_) => ReportPage(expenses: _expenses),
                    ),
                  );
                },
              ),
              ListTile(
                leading: const Icon(Icons.calendar_month_outlined),
                title: const Text('月のレポート'),
                onTap: () async {
                  Navigator.pop(context);
                  await Navigator.push(
                    context,
                    MaterialPageRoute(
                      builder: (_) => MonthlyReportPage(
                        periodStart: currentCycleStart,
                        periodEnd: currentCycleEnd,
                      ),
                    ),
                  );
                },
              ),
              const Divider(),
              ListTile(
                leading: const Icon(Icons.backup_outlined),
                title: const Text('バックアップと復元'),
                onTap: () async {
                  Navigator.pop(context);
                  final result = await Navigator.push(
                    context,
                    MaterialPageRoute(
                      builder: (_) => const BackupRestorePage(),
                    ),
                  );
                  if (result == true) {
                    await _loadInitialData();
                  }
                },
              ),
              ListTile(
                leading: const Icon(Icons.restore),
                title: const Text('購入を復元'),
                onTap: () async {
                  Navigator.pop(context);
                  final result = await Navigator.push(
                    context,
                    MaterialPageRoute(
                      builder: (_) => const PremiumPage(),
                    ),
                  );
                  if (result == true) {
                    await _loadPremiumStatus();
                  }
                },
              ),
              ListTile(
                leading: const Icon(Icons.description_outlined),
                title: const Text('利用規約'),
                onTap: () {
                  Navigator.pop(context);
                },
              ),
              ListTile(
                leading: const Icon(Icons.privacy_tip_outlined),
                title: const Text('プライバシーポリシー'),
                onTap: () {
                  Navigator.pop(context);
                },
              ),
            ],
          ),
        ),
      ),
      appBar: AppBar(
        centerTitle: true,
        title: const Text('財布の余命'),
        actions: [
            if (kDebugMode)
    IconButton(
      onPressed: _openDebugTimeMenu,
      icon: const Icon(Icons.bug_report_outlined),
      tooltip: 'デバッグ時刻',
    ),
          IconButton(
            onPressed: () async {
              final result = await Navigator.push(
                context,
                MaterialPageRoute(
                  builder: (_) => const BudgetPage(),
                ),
              );

              if (result == true) {
                await _loadInitialData();
              }
            },
            icon: const Icon(Icons.savings_outlined),
            tooltip: '予算設定',
          ),
        ],
      ),
      body: SafeArea(
        child: ListView(
          padding: const EdgeInsets.all(16),
          children: [
            SizedBox(
              width: double.infinity,
              child: ElevatedButton.icon(
                onPressed: _isGeneratingMonthlyReport
                    ? null
                    : _generateMonthlyReportForTest,
                icon: const Icon(Icons.auto_awesome_outlined),
                label: const Text('月レポート作成（テスト）'),
              ),
            ),
            if (_monthlyReportStatusMessage != null) ...[
              const SizedBox(height: 8),
              Text(
                _monthlyReportStatusMessage!,
                style: theme.textTheme.bodySmall?.copyWith(
                  color: Colors.black54,
                  fontWeight: FontWeight.w600,
                ),
              ),
            ],
            const SizedBox(height: 12),
            SummaryCard(
              isLoading: _isInitialLoading,
              remainingBudget: remainingBudget,
              walletLifeDays: realWalletLifeDays,
              remainingPeriodDays: remainingPeriodDays,
              totalBudget: _totalBudget,
              usedAmount: usedAmount,
              remainingTitle: remainingBudgetResult.title,
              remainingMessage: remainingBudgetResult.message,
              remainingSubMessage: remainingBudgetResult.subMessage,
              cyclePeriod: cyclePeriodText,
              dailySpendingPaceYen: dailySpendingPaceYen,
              plannedDailyBudgetYen: plannedDailyBudgetYen,
            ),
            const SizedBox(height: 16),
            InkWell(
              onTap: () {
                Navigator.push(
                  context,
                  MaterialPageRoute(
                    builder: (_) => RankDetailPage(
                      rankResult: _rankResult,
                    ),
                  ),
                );
              },
              borderRadius: BorderRadius.circular(22),
              child: Container(
                padding: const EdgeInsets.all(16),
                decoration: BoxDecoration(
                  color: Colors.white,
                  borderRadius: BorderRadius.circular(22),
                  border: Border.all(color: const Color(0xFFF0F0F0)),
                ),
                child: Row(
                  children: [
                    _rankBadge(_rankResult?.rankKey, size: 52),
                    const SizedBox(width: 12),
Expanded(
  child: Column(
    crossAxisAlignment: CrossAxisAlignment.start,
    children: [
      Row(
        children: [
          Expanded(
            child: Text(
              'やりくりランク',
              style: theme.textTheme.titleMedium?.copyWith(
                fontWeight: FontWeight.w800,
              ),
            ),
          ),
          const Icon(
            Icons.chevron_right_rounded,
            color: Colors.black45,
          ),
        ],
      ),
      const SizedBox(height: 4),
      Text(
        _rankResult?.rankLabel ?? 'スターター',
        style: theme.textTheme.titleLarge?.copyWith(
          fontWeight: FontWeight.w800,
          color: Colors.black87,
        ),
      ),
      const SizedBox(height: 10),
      Wrap(
        spacing: 8,
        runSpacing: 8,
        children: [
          Container(
            padding: const EdgeInsets.symmetric(
              horizontal: 10,
              vertical: 6,
            ),
            decoration: BoxDecoration(
              color: const Color(0xFFF8F9FC),
              borderRadius: BorderRadius.circular(999),
              border: Border.all(color: const Color(0xFFEDEDED)),
            ),
            child: Text(
              '${_rankResult?.streak ?? 0}ヶ月連続で予算内',
              style: theme.textTheme.bodySmall?.copyWith(
                fontWeight: FontWeight.w700,
                color: Colors.black87,
              ),
            ),
          ),
        ],
      ),
    ],
  ),
),
                  ],
                ),
              ),
            ),
            if (dangerCategories.isNotEmpty) ...[
            const SizedBox(height: 16),
            Container(
              padding: const EdgeInsets.all(16),
              decoration: BoxDecoration(
                color: const Color(0xFFFFF4F1),
                borderRadius: BorderRadius.circular(20),
                border: Border.all(color: const Color(0xFFFFD7CC)),
              ),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    '⚠ 危険カテゴリ',
                    style: theme.textTheme.titleMedium?.copyWith(
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                  const SizedBox(height: 12),
                  if (dangerCategories.isEmpty)
                    const Text('カテゴリ予算を設定すると、危険カテゴリがここに表示されます。')
                  else
                    ...dangerCategories.map((category) {
                      return Padding(
                        padding: const EdgeInsets.only(bottom: 10),
                        child: Row(
                          children: [
                            Text(
                              category['badge'] as String,
                              style: const TextStyle(fontSize: 22),
                            ),
                            const SizedBox(width: 10),
                            Expanded(
                              child: Column(
                                crossAxisAlignment: CrossAxisAlignment.start,
                                children: [
                                  Text(
                                    category['name'] as String,
                                    style: theme.textTheme.titleSmall?.copyWith(
                                      fontWeight: FontWeight.w700,
                                    ),
                                  ),
                                  const SizedBox(height: 2),
                                  Builder(builder: (_) {
                                    final remaining = category['remaining'] as int;
                                    final usageRate = category['usageRate'] as double;

                                    Color textColor;
                                    if (remaining < 0) {
                                      textColor = Colors.red;
                                    } else if (usageRate >= 0.9) {
                                      textColor = Colors.red;
                                    } else if (usageRate >= 0.75) {
                                      textColor = Colors.orange;
                                    } else {
                                      textColor = Colors.black87;
                                    }

                                    if (remaining < 0) {
                                      return Text(
                                        '予算オーバー ¥${_formatYen(remaining.abs())}',
                                        style: TextStyle(
                                          color: textColor,
                                          fontWeight: FontWeight.w700,
                                        ),
                                      );
                                    }

                                    return Text(
                                      '残り ¥${_formatYen(remaining)} (${(usageRate * 100).round()}%)',
                                      style: TextStyle(
                                        color: textColor,
                                        fontWeight: FontWeight.w600,
                                      ),
                                    );
                                  }),
                                ],
                              ),
                            ),
                            Builder(builder: (_) {
                              final remaining = category['remaining'] as int;
                              final usageRate = category['usageRate'] as double;

                              Color color;

                              if (remaining < 0) {
                                color = Colors.red; // 予算オーバー
                              } else if (usageRate >= 0.9) {
                                color = Colors.red; // 危険
                              } else if (usageRate >= 0.75) {
                                color = Colors.orange; // 注意
                              } else {
                                color = Colors.grey;
                              }

                              return Icon(
                                Icons.warning_amber_rounded,
                                color: color,
                              );
                            }),
                          ],
                        ),
                      );
                    }),
                ],
              ),
            ),
            ],
            const SizedBox(height: 16),
            ...roastCards.expand((card) => [
                  RoastCard(
                    title: card.title,
                    message: card.message,
                    subMessage: card.subMessage,
                  ),
                  const SizedBox(height: 12),
                ]),
            const SizedBox(height: 16),
            Container(
              padding: const EdgeInsets.fromLTRB(16, 14, 16, 16),
              decoration: BoxDecoration(
                color: Colors.white,
                borderRadius: BorderRadius.circular(22),
                border: Border.all(color: const Color(0xFFF0F0F0)),
              ),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    'カテゴリ別予算',
                    style: theme.textTheme.titleLarge?.copyWith(
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                  const SizedBox(height: 4),
                  Text(
                    'カテゴリごとの進み方を確認できます',
                    style: theme.textTheme.bodySmall?.copyWith(
                      color: Colors.black54,
                      fontWeight: FontWeight.w500,
                    ),
                  ),
                  const SizedBox(height: 12),
                  Builder(
                    builder: (context) {
                      final hasOverflowCategory = categorySummaries.any(
                        (c) => (c['remaining'] as int) < 0,
                      );

                      return SizedBox(
                        height: hasOverflowCategory ? 180 : 164,
                    child: categorySummaries.isEmpty
                        ? Container(
                            padding: const EdgeInsets.all(16),
                            decoration: BoxDecoration(
                              color: Colors.white,
                              borderRadius: BorderRadius.circular(18),
                            ),
                            child: const Center(
                              child: Text('カテゴリ予算を設定するとここに一覧が表示されます。'),
                            ),
                          )
                        : Column(
                            children: [
                              Expanded(
                                child: Scrollbar(
                                  controller: _categoryScrollController,
                                  thumbVisibility: false,
                                  trackVisibility: false,
                                  radius: const Radius.circular(999),
                                  thickness: 4,
                                  scrollbarOrientation: ScrollbarOrientation.bottom,
                                  child: ListView.separated(
                                    controller: _categoryScrollController,
                                    scrollDirection: Axis.horizontal,
                                  itemCount: categorySummaries.length,
                                    separatorBuilder: (_, __) => const SizedBox(width: 10),
                                    itemBuilder: (context, index) {
                                      final category = categorySummaries[index];
                                      final budget = category['budget'] as int;
                                      final used = category['used'] as int;
                                      final progress = budget == 0
                                          ? 0.0
                                          : (used / budget).clamp(0.0, 1.0);

                                      return Container(
                                        width: 150,
                                        padding: const EdgeInsets.all(14),
                                        decoration: BoxDecoration(
                                          color: Colors.white,
                                          borderRadius: BorderRadius.circular(18),
                                          border: Border.all(
                                            color: const Color(0xFFEDEDED),
                                          ),
                                        ),
                                        child: Column(
                                          crossAxisAlignment: CrossAxisAlignment.start,
                                          children: [
                                            Text(
                                              '${category['badge']} ${category['name']}',
                                              style: theme.textTheme.titleSmall?.copyWith(
                                                fontWeight: FontWeight.bold,
                                              ),
                                            ),
                                            const SizedBox(height: 4),
                                            Text(
                                              '予算 ¥${_formatYen(budget)}',
                                              style: theme.textTheme.bodySmall?.copyWith(
                                                color: Colors.black54,
                                                fontWeight: FontWeight.w600,
                                              ),
                                            ),
                                            const SizedBox(height: 8),
                                            Builder(builder: (_) {
                                              final remaining = category['remaining'] as int;
                                              final usageRate = category['usageRate'] as double;

                                              Color textColor;
                                              if (remaining < 0) {
                                                textColor = Colors.red;
                                              } else if (usageRate >= 0.9) {
                                                textColor = Colors.red;
                                              } else if (usageRate >= 0.75) {
                                                textColor = Colors.orange;
                                              } else {
                                                textColor = Colors.black87;
                                              }

                                              if (remaining < 0) {
                                                return Text(
                                                  '予算オーバー ¥${_formatYen(remaining.abs())}',
                                                  style: TextStyle(
                                                    color: textColor,
                                                    fontWeight: FontWeight.w700,
                                                  ),
                                                );
                                              }
                                              return Text(
                                                '残り ¥${_formatYen(remaining)}',
                                                style: TextStyle(
                                                  color: textColor,
                                                  fontWeight: FontWeight.w600,
                                                ),
                                              );
                                            }),
                                            const SizedBox(height: 8),
                                            ClipRRect(
                                              borderRadius: BorderRadius.circular(999),
                                              child: LinearProgressIndicator(
                                                value: progress,
                                                minHeight: 8,
                                              ),
                                            ),
                                            const SizedBox(height: 6),
                                            Text('${(progress * 100).round()}% 使用'),
                                          ],
                                        ),
                                      );
                                    },
                                  ),
                                ),
                              ),
                              const SizedBox(height: 6),
                            ],
                          ),
                      );
                    },
                  ),
                ],
              ),
            ),
            const SizedBox(height: 16),
            const SizedBox(height: 16),
Container(
  padding: const EdgeInsets.all(16),
  decoration: BoxDecoration(
    color: Colors.white,
    borderRadius: BorderRadius.circular(22),
    border: Border.all(color: const Color(0xFFF0F0F0)),
  ),
  child: Column(
    crossAxisAlignment: CrossAxisAlignment.start,
    children: [
      Text(
        '分析',
        style: theme.textTheme.titleLarge?.copyWith(
          fontWeight: FontWeight.bold,
        ),
      ),
      const SizedBox(height: 4),
      Text(
        '支出の傾向や振り返りを確認できます',
        style: theme.textTheme.bodySmall?.copyWith(
          color: Colors.black54,
          fontWeight: FontWeight.w500,
        ),
      ),
      const SizedBox(height: 12),
      InkWell(
        onTap: () {
          Navigator.push(
            context,
            MaterialPageRoute(
              builder: (_) => RankingPage(
                expenses: _expenses,
                formatYen: _formatYen,
              ),
            ),
          );
        },
        borderRadius: BorderRadius.circular(16),
        child: Container(
          width: double.infinity,
          padding: const EdgeInsets.all(14),
          decoration: BoxDecoration(
            color: const Color(0xFFF8F9FC),
            borderRadius: BorderRadius.circular(16),
            border: Border.all(color: const Color(0xFFEDEDED)),
          ),
          child: Row(
            children: [
              Container(
                width: 42,
                height: 42,
                decoration: BoxDecoration(
                  color: const Color(0xFFFFF1EA),
                  borderRadius: BorderRadius.circular(14),
                ),
                alignment: Alignment.center,
                child: const Icon(Icons.pie_chart_outline_rounded),
              ),
              const SizedBox(width: 12),
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      '何に使っている？',
                      style: theme.textTheme.titleSmall?.copyWith(
                        fontWeight: FontWeight.w800,
                      ),
                    ),
                    const SizedBox(height: 2),
                    Text(
                      'カテゴリ別の支出ランキングを見る',
                      style: theme.textTheme.bodySmall?.copyWith(
                        color: Colors.black54,
                        fontWeight: FontWeight.w500,
                      ),
                    ),
                  ],
                ),
              ),
              const SizedBox(width: 8),
              const Icon(Icons.chevron_right_rounded),
            ],
          ),
        ),
      ),
      const SizedBox(height: 10),
      InkWell(
        onTap: () {
          Navigator.push(
            context,
            MaterialPageRoute(
              builder: (_) => const MoneyUsagePage(),
            ),
          );
        },
        borderRadius: BorderRadius.circular(16),
        child: Container(
          width: double.infinity,
          padding: const EdgeInsets.all(14),
          decoration: BoxDecoration(
            color: const Color(0xFFF8F9FC),
            borderRadius: BorderRadius.circular(16),
            border: Border.all(color: const Color(0xFFEDEDED)),
          ),
          child: Row(
            children: [
              Container(
                width: 42,
                height: 42,
                decoration: BoxDecoration(
                  color: const Color(0xFFEAF4FF),
                  borderRadius: BorderRadius.circular(14),
                ),
                alignment: Alignment.center,
                child: const Icon(Icons.bar_chart_rounded),
              ),
              const SizedBox(width: 12),
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      'どう使ってる？',
                      style: theme.textTheme.titleSmall?.copyWith(
                        fontWeight: FontWeight.w800,
                      ),
                    ),
                    const SizedBox(height: 2),
                    Text(
                      '総額・カテゴリ・お店・月別で分析',
                      style: theme.textTheme.bodySmall?.copyWith(
                        color: Colors.black54,
                        fontWeight: FontWeight.w500,
                      ),
                    ),
                  ],
                ),
              ),
              const SizedBox(width: 8),
              const Icon(Icons.chevron_right_rounded),
            ],
          ),
        ),
      ),
    ],
  ),
),
            const SizedBox(height: 16),
           Text(
              'タイムライン',
              style: theme.textTheme.titleLarge?.copyWith(
                fontWeight: FontWeight.bold,
              ),
            ),
            const SizedBox(height: 12),
            if (currentCycleExpenses.isEmpty) ...[
              Container(
                padding: const EdgeInsets.all(16),
                decoration: BoxDecoration(
                  color: Colors.white,
                  borderRadius: BorderRadius.circular(20),
                ),
                child: const Text('まだ支出がありません。最初の支出を追加してみましょう。'),
              ),
              const SizedBox(height: 90),
            ] else ...[
              ...currentCycleExpenses.take(10).expand((expense) => [
                    Dismissible(
                      key: ValueKey(expense.id),
                      direction: DismissDirection.endToStart,
                      background: Container(
                        decoration: BoxDecoration(
                          color: const Color(0xFFFFF1F1),
                          borderRadius: BorderRadius.circular(18),
                        ),
                      ),
                      secondaryBackground: Container(
                        alignment: Alignment.centerRight,
                        padding: const EdgeInsets.symmetric(horizontal: 20),
                        decoration: BoxDecoration(
                          color: const Color(0xFFFFE1E1),
                          borderRadius: BorderRadius.circular(18),
                        ),
                        child: const Icon(
                          Icons.delete_outline,
                          color: Color(0xFFD64B4B),
                          size: 28,
                        ),
                      ),
                      confirmDismiss: (_) async {
                        final deleted = await _deleteExpense(expense);
                        return deleted;
                      },
                      child: TimelineItem(
                        title: expense.storeName,
                        subtitle: expense.category,
                        amount: '¥${_formatYen(expense.amount)}',
                        icon: _iconForCategory(expense.category),
                        date: _formatTimelineDate(expense.createdAt),
                        onEdit: () async {
                          await _editExpense(expense);
                        },
                        onDelete: () async {
                          await _deleteExpense(expense);
                        },
                      ),
                    ),
                    if (expense.futureLogMessage != null) ...[
                      const SizedBox(height: 10),
                      FutureLogItem(message: expense.futureLogMessage!),
                    ],
                    const SizedBox(height: 10),
                  ]),
                  Center(
                    child: TextButton(
                      onPressed: _openFullTimeline,
                      child: const Text('一覧へ'),
                    ),
                ),
              const SizedBox(height:  70),
            ]
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton.extended(
        onPressed: () async {
          final result = await Navigator.push(
            context,
            MaterialPageRoute(
              builder: (_) => const AddExpensePage(),
            ),
          );

          if (result == true) {
            await _loadInitialData();
          }
        },
        label: const Text('支出を追加'),
        icon: const Icon(Icons.add),
      ),
    );
  }

  Future<Expense?> _editExpense(Expense expense) async {
  final result = await Navigator.push(
    context,
    MaterialPageRoute(
      builder: (_) => AddExpensePage(initialExpense: expense),
    ),
  );

  if (result == true) {
    await _loadInitialData();

    for (final item in _expenses) {
      if (item.id == expense.id) return item;
    }
  }

  return null;
}

Future<bool> _deleteExpense(Expense expense) async {
  final shouldDelete = await showDialog<bool>(
    context: context,
    builder: (dialogContext) {
      return AlertDialog(
        title: const Text('支出を削除しますか？'),
        content: Text('${expense.storeName} の支出を削除します。'),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(dialogContext, false),
            child: const Text('キャンセル'),
          ),
          TextButton(
            onPressed: () => Navigator.pop(dialogContext, true),
            child: const Text('削除'),
          ),
        ],
      );
    },
  );

  if (shouldDelete != true) return false;

  await IsarService.deleteExpense(expense.id);
  if (_isPremium) {
    await ExpenseSyncService.deleteExpense(expense.id);
  }
  await _loadInitialData();
  return true;
}


void _openFullTimeline() {
  Navigator.push(
    context,
    MaterialPageRoute(
      builder: (_) => TimelinePage(
        expenses: _currentCycleExpensesCache,
        formatYen: _formatYen,
        categoryLabel: (category) => category,
        iconForCategory: _iconForCategory,
        formatTimelineDate: _formatTimelineDate,
        onEditExpense: _editExpense,
        onDeleteExpense: _deleteExpense,
      ),
    ),
  );
}

Future<void> _autoGenerateMonthlyReportIfNeeded() async {
  final budgetSetting = await IsarService.getBudgetSetting();
  if (budgetSetting == null) return;
  if (budgetSetting.totalBudget <= 0) return;

  final cycleStartDay = budgetSetting.cycleStartDay.clamp(1, 28);
  // final now = DateTime.now();
  final now = getNow();
  final baseStart = now.day >= cycleStartDay
      ? DateTime(now.year, now.month, cycleStartDay)
      : DateTime(now.year, now.month - 1, cycleStartDay);

  final currentCycleStart = DateTime(
    baseStart.year,
    baseStart.month + _cycleOffsetMonths,
    baseStart.day,
  );

  try {
    await MonthlyReportService.autoGenerateIfNeeded(
      now: now,
      currentCycleStart: currentCycleStart,
      cycleStartDay: cycleStartDay,
    );
  } catch (e) {
    debugPrint('[MonthlyReport] auto generate skipped: $e');
  }
}

  Future<List<({String title, String message, String subMessage})>>
      _buildRoastCards({
    required List<Expense> currentCycleExpenses,
    required int totalBudget,
    required int usedAmount,
    required DateTime start,
    required DateTime endInclusive,
    required List<Map<String, dynamic>> dangerCategories,
  }) async {
    final latestCategoryTagUsedAmounts = <ExpenseJudgeTag, int>{};
    if (currentCycleExpenses.isNotEmpty) {
      final latestCategory = currentCycleExpenses.first.category;
      final categoryExpenses = currentCycleExpenses
          .where((expense) => expense.category == latestCategory)
          .toList();

      for (final expense in categoryExpenses) {
        final judge = ExpenseJudgeService.judge(
          expense: expense,
          totalBudget: totalBudget,
        );

        for (final tag in judge.tags) {
          latestCategoryTagUsedAmounts[tag] =
              (latestCategoryTagUsedAmounts[tag] ?? 0) + expense.amount;
        }
      }
    }

    final categoryCountMap = <String, int>{};
    final categoryAmountMap = <String, int>{};

    for (final expense in currentCycleExpenses) {
      final category = expense.category;
      categoryCountMap[category] = (categoryCountMap[category] ?? 0) + 1;
      categoryAmountMap[category] =
          (categoryAmountMap[category] ?? 0) + expense.amount;
    }

    final latestCategoryBudget = currentCycleExpenses.isEmpty
        ? 0
        : (() {
            final latestCategory = currentCycleExpenses.first.category;
            final matchedCategory = _budgetSetting?.categories
                .where((category) => category.name == latestCategory)
                .toList();
            if (matchedCategory == null || matchedCategory.isEmpty) return 0;
            return matchedCategory.first.budget;
          })();

    final latestCategoryUsed = currentCycleExpenses.isEmpty
        ? 0
        : (() {
            final latestCategory = currentCycleExpenses.first.category;
            return currentCycleExpenses
                .where((expense) => expense.category == latestCategory)
                .fold<int>(0, (sum, expense) => sum + expense.amount);
          })();

    final roastResult = await RoastService.build(
      totalBudget: totalBudget,
      usedAmount: usedAmount,
      expenses: currentCycleExpenses,
      dangerCategories: dangerCategories.take(3).toList(),
      latestCategoryBudget: latestCategoryBudget,
      latestCategoryUsed: latestCategoryUsed,
      cycleStart: start,
      cycleEnd: endInclusive,
      latestCategoryTagUsedAmounts: latestCategoryTagUsedAmounts,
    );

    final roastCards = <({String title, String message, String subMessage})>[];

    final subLines = roastResult.subMessage
        .split('\n')
        .map((text) => text.trim())
        .where((text) => text.isNotEmpty)
        .toList();

    final hasLayeredRoast = subLines.length >= 3;

    if (hasLayeredRoast) {
      final monthlySubMessage = subLines.isNotEmpty ? subLines.first : '';
      final latestMessage = subLines.length >= 2 ? subLines[1] : '';
      final latestSubMessage =
          subLines.length >= 3 ? subLines.sublist(2).join('\n') : '';

      roastCards.add((
        title: roastResult.title,
        message: roastResult.message,
        subMessage: monthlySubMessage,
      ));

      roastCards.add((
        title: '財布からもうひとこと',
        message: latestMessage,
        subMessage: latestSubMessage,
      ));
    } else {
      roastCards.add((
        title: roastResult.title,
        message: roastResult.message,
        subMessage: roastResult.subMessage,
      ));
    }

    return roastCards;
  }
  }